### ISSUE TITLE
`ca1` source not showing most recent opinions 

### ISSUE THREAD

**Issue by grossir** [freelawproject/juriscraper#1017]
Current scraper uses this [endpoint](http://media.ca1.uscourts.gov/cgi-bin/opinions.pl/?FROMDATE=01%2F24%2F2024&TODATE=05%2F01%2F2024&puid=) which shows an opinion published in February 2nd 2024 as the most recent one. This is also the newest opinion from `ca1` that we have on [Courtlistener](https://www.courtlistener.com/?q=court_id%3Aca1&type=o&order_by=dateFiled%20desc&stat_Precedential=on&stat_Non-Precedential=on&stat_Errata=on&stat_Unknown%20Status=on) . However, the RSS feeds show more recent [opinions](https://www.ca1.uscourts.gov/opnrss?page=1), between April 30 2024 and  April 2nd 2024.

UPDATE: A new endpoint with fresh data is available [here](https://www.ca1.uscourts.gov/opn/aci?field_opn_csno_value_op=starts&OPINNUM=&field_opn_short_title_value=&field_opn_issdate_value%5Bmin%5D%5Bdate%5D=+02%2F01%2F2024&field_opn_issdate_value%5Bmax%5D%5Bdate%5D=+03%2F01%2F2024) 

Will implement a fix for current opinions, and a backscraper for the months we are missing

@flooie

**Comment by grossir** [comment]
Of note are the comments from one of the original authors, for which I sadly found no new place
```
            s = "1996/05/30"  # My life is thus lain to waste.
```
```
            s = s.replace("O1-", "01-")  # I grow older, the input grows worse.

```

**Comment by grossir** [comment]
To collect the opinions we are missing from February to present:
(will need to bump juriscraper and courtlistener, but the backscraper PR in courtlistener is already merged)
```
docker exec -it cl-django python /opt/courtlistener/manage.py cl_back_scrape_opinions --courts juriscraper.opinions.united_states.federal_appellate.ca1 --backscrape-start=02/02/2024 --backscrape-end=04/30/2024
```

**Comment by grossir** [comment]
Backscraper was ran by Ramiro, and the gap has been closed. Closing this issue as completed

**Comment by flooie** [comment]
wahoo
