### ISSUE TITLE
`site.request["parameters"]` defined by an inheriting scraper is never used

### ISSUE THREAD

**Issue by grossir** [freelawproject/juriscraper#1112]
A user of Juriscraper may want to use the defined interface through `self.request`. However, it does not behave as expected. I was trying to understand why the `minn` scraper had to redefine `request_url_get`, instead of just using `self.request["parameters"]`, `self.request["headers"]` and `self.request["verify"]`. The explanation is below

https://github.com/freelawproject/juriscraper/blob/6a645346dce8f4ab4173a9a196093df7aa2e9120/juriscraper/opinions/united_states/state/minn.py#L43-L53

------------------
Somewhat confusingly, there are 2 "parameters" attributes defined on AbstractSite

`self.parameters` which is used only on POST requests as the data argument
https://github.com/freelawproject/juriscraper/blob/6a645346dce8f4ab4173a9a196093df7aa2e9120/juriscraper/AbstractSite.py#L68

`self.request["parameters"]` which, if defined explicitly in an inheriting Site, will never be used
https://github.com/freelawproject/juriscraper/blob/6a645346dce8f4ab4173a9a196093df7aa2e9120/juriscraper/AbstractSite.py#L48-L58

This is due to `_download` being called by `_parse` without a `request_dict` argument
https://github.com/freelawproject/juriscraper/blob/6a645346dce8f4ab4173a9a196093df7aa2e9120/juriscraper/AbstractSite.py#L139-L142

The effect of this, is that the existing `self.request["parameters"]` will always be deleted by `process_request_parameters`
https://github.com/freelawproject/juriscraper/blob/6a645346dce8f4ab4173a9a196093df7aa2e9120/juriscraper/AbstractSite.py#L322-L335

Since the default is always an empty dict
https://github.com/freelawproject/juriscraper/blob/6a645346dce8f4ab4173a9a196093df7aa2e9120/juriscraper/AbstractSite.py#L354-L359

------------------
Related to #1106 and #1064

**Comment by mlissner** [comment]
Nice. Looks like you've got the fix figured out too, right? I'll put this on your backlog. Thank you.

**Comment by flooie** [comment]
while we are fixing things - @grossir do you think we should fix the data/parameters overlapping language?  have you noticed this?

**Comment by flooie** [comment]
this is something I've wanted to get to for a while.  thanks for tackling this.  this should make things much nicer
