### ISSUE TITLE
`nh` scraper is blocking "Juriscraper" user agent

### ISSUE THREAD

**Issue by grossir** [freelawproject/juriscraper#1128]
We are getting a JSONDecodeError in Sentry, but below that there is a 403 Forbidden response

Text:
```
Access Denied
You don't have permission to access "http://www.courts.nh.gov/content/api/documents?" on this server.
Reference #18.264ede17.1724262770.3c5420e3

https://errors.edgesuite.net/18.264ede17.1724262770.3c5420e3
```

Headers:
```
{'Mime-Version': '1.0', 'Content-Type': 'text/html', 'Content-Length': '409', 'Cache-Control': 'max-age=0', 'Date': 'Wed, 21 Aug 2024 17:53:34 GMT', 'Connection': 'close', 'Strict-Transport-Security': 'max-age=86400'}
```

Sentry Issue: [COURTLISTENER-80A](https://freelawproject.sentry.io/issues/5712371490/?referrer=github_integration)

```
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
  File "requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "__init__.py", line 514, in loads
    return _default_decoder.decode(s)
  File "simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
  File "cl/scrapers/management/commands/cl_scrape_opinions.py", line 413, in handle
    self.parse_and_scrape_site(mod, options)
  File "cl/scrapers/management/commands/cl_scrape_opinions.py", line 376, in parse_and_scrape_site
    site = mod.Site().parse()
```

**Comment by grossir** [comment]
While inspecting this problem, I also noticed that the source now has neutral citations

`reporters-db` seems to support it
```
In [1]: from eyecite import get_citations
In [2]: get_citations("2024 N.H. 42")
Out[2]: [FullCaseCitation('2024 N.H. 42', groups={'volume': '2024', 'reporter': 'N.H.', 'page': '42'}, metadata=FullCaseCitation.Metadata(parenthetical=None, pin_cite=None, year=None, court=None, plaintiff=None, defendant=None, extra=None))]
```

> To cite an opinion issued after January 1, 2024, review [this notice](https://www.courts.nh.gov/sites/g/files/ehbemt471/files/inline-documents/sonh/1-18-2024-notice-concerning-adoption-of-neutral-citation.pdf) .pdf Icon concerning neutral citation

> Notice — Adoption of Neutral Citation Form
Beginning on January 1, 2024, the Supreme Court of New Hampshire
will add a neutral citation form (also referred to as public domain citation) to its
published opinions. Neutral citation is a form of case citation that is
independent of a local or regional reporter. The citation begins with the year
issued, followed by the jurisdiction, and concludes with the opinion number.
For example, the first opinion of the court issued after January 1, 2024, will
receive a citation of 2024 N.H. 1.
Opinions with neutral citation will include individually-numbered
paragraphs. To cite an opinion using neutral citation, the writer will refer to
the paragraph that contains the proposition cited, rather than to the page.
Therefore, a full case citation will include the following: (1) the case name; (2)
the year; (3) the jurisdiction (N.H.); (4) the opinion number for that year; and (5)
the paragraph number(s). For instance, if the information cited is contained in
the fifth and sixth paragraphs of the opinion, the full citation would appear as
follows: Kennedy v. Acme, Inc., 2024 N.H. 1, ¶¶ 5-6. A short cite to the same
material would be Kennedy, 2024 N.H. 1, ¶¶5-6.
Opinions issued after January 1, 2024, will continue to be published in
the New Hampshire Reports until further notice. They will also continue to be
posted to the Supreme Court of New Hampshire website. During this period,
the writer may continue to cite the New Hampshire Reports or may use neutral
citation. Adding the neutral citation form at this time not only enables
opinions of the Supreme Court to be assigned a permanent citation
immediately upon online issuance without waiting for the publication of an
official paginated report, but also prepares for online issuance as the exclusive
method of opinion publication. See RSA 505:8, I.


![image](https://github.com/user-attachments/assets/d9460601-fc89-4caa-80f5-3dcfcb6c77b5)

**Comment by mlissner** [comment]
That's wonderful about the neutral citations. I'd love to figure out who made this happen there, and to chat with them. It looks like we might be able to work the grapevine a bit, according to the contact here: https://github.com/freelawproject/crm/issues/477. 

On the substance, let's add this to @flooie's list to ① become friends and applaud their neutral citation usage, and ② get access restored.

**Comment by grossir** [comment]
About access, I have been testing, and the scraper works by changing the User-Agent and a few other headers, so we can use that provisionally

**Comment by mlissner** [comment]
Great!

**Comment by grossir** [comment]
About the neutral citations, giving it another look, the reporter "N.H." on reporters-db maps to a "STATE" type reporter on Courtlistener, not a "NEUTRAL" type, so, it would not be proper to use that one. We should probably solve that issue before collecting these citations

On the reporter's page, we jump from volume 172 to "volume" 2009, which actually stands for a year:

https://www.courtlistener.com/c/nh/

**Comment by mlissner** [comment]
You're absolutely right, we should fix these before we gather the citations. Very nice catch.
