### ISSUE TITLE
`wisctapp` not assigning "Published" status to published opinions

### ISSUE THREAD

**Issue by grossir** [freelawproject/juriscraper#1164]
A bug in `wisctapp`, some (maybe all) "Published" opinions marked as "Unpublished". [Example](https://www.courtlistener.com/opinion/10109548/city-of-stoughton-v-erik-j-olson/?q=court_id%3Awisctapp&type=o&order_by=dateFiled+desc&stat_Precedential=on&stat_Non-Precedential=on&stat_Errata=on&filed_after=06%2F28%2F2019&filed_before=08%2F19%2F2024&page=3) , [Example 2](https://www.courtlistener.com/opinion/10109661/brian-nelson-v-david-loessin/?q=court_id%3Awisctapp&type=o&order_by=dateFiled+desc&stat_Precedential=on&stat_Non-Precedential=on&stat_Errata=on&filed_after=06%2F28%2F2019&filed_before=08%2F19%2F2024&page=4)

Easy to spot them because the ones that should be marked as published have neutral citations

**Comment by flooie** [comment]
This has been fixed on the CL side.
