### ISSUE TITLE
`ohioctapp` scrapers not working

### ISSUE THREAD

**Issue by grossir** [freelawproject/juriscraper#1193]
This problem is not showing on Sentry, but we haven't got any data since September 16th, and there are more recent opinions on the source. I am monitoring this court to see the effects on https://github.com/freelawproject/juriscraper/issues/1135

**Comment by grossir** [comment]
After looking into the `kanctapp` issue, it seems to be scraping the Supreme Court page, instead of each circuit / district pages

**Comment by flooie** [comment]
hm...
