### ISSUE TITLE
`utah` scraper is failing

### ISSUE THREAD

**Issue by grossir** [freelawproject/juriscraper#1220]
The [latest case](https://www.courtlistener.com/?q=court_id%3Autah&type=o&order_by=dateFiled%20desc&stat_Published=on) in the DB is from September 5, 2024; but there is 1 case from October.  The scraper is failing silently, it is not picking up any case, probably from changes in the HTML due to a migration to the new site ? (Check the screenshot below)

Found using the query described here https://github.com/freelawproject/courtlistener/issues/3950

![Image](https://github.com/user-attachments/assets/4c043321-2b28-41d3-985a-dacfbc5f373e)

**Comment by flooie** [comment]
Thanks

**Comment by flooie** [comment]
we will probably have to update this again soon when they publish the new page but such is the way things go
