### ISSUE TITLE
Logging location should be configurable

### ISSUE THREAD

**Issue by voutilad** [freelawproject/juriscraper#128]
Noticed while working on issue #59, it seems there's some hardcoding of log locations. These (if more than one) should probably be set in a config file or environment setting. Ideally the default would also be a relative location to the current working directory and not a hardcoded path most likely not existing on most machines (especially non-Un*x).

```
Warning: No such file or directory: /var/log/juriscraper/debug.log. Have you created the directory for the log?
Juriscraper will continue to run, but will not create logs.
```

**Comment by mlissner** [comment]
Maybe a good technique is to have it log to /var/log/juriscraper if that exists, and to fall back to stdout if not. 

I'm not terribly concerned about Windows compatibility though, FWTW.

**Comment by mlissner** [comment]
I fixed this the easy way. Could still be improved by supporting an env, but this is progress, which is all I aim for...
