### ISSUE TITLE
Scraper Tests hiding failures on Python 2.7.

### ISSUE THREAD

**Issue by voutilad** [freelawproject/juriscraper#175]
Scraper tests are failing yet not failing the tests on Python 2.7, masking some old syntax errors like print statements and old-style exception statements.

**Comment by arderyp** [comment]
I've also noticed issues in `juriscraper/sample_caller.py` running p3.  They are pretty simple to fix, and I started to do it, but then got into the string_utils nest of issues, which I know someone else is working on.  I can look at sample_caller if need be, just let me know.  Or you can run a quick test with the scraper I am about to push:

(from p3 virtualenv)
```
python juriscraper/sample_caller.py -c opinions.united_states.state.nyag --backscrape
```

**Comment by voutilad** [comment]
Just getting around to running that command. Definitely fails on my machine in Python 3.6 due to `urllib2` changes. Seems that file isn't Python3 ready. Going to poke at it now.

**Comment by mlissner** [comment]
Guessing we can close this?

**Comment by voutilad** [comment]
I believe so.

**Comment by arderyp** [comment]
Awesome!
