### ISSUE TITLE
When scraping example files, verify that scraped results match a test fixture

### ISSUE THREAD

**Issue by mlissner** [freelawproject/juriscraper#176]
This should be pretty simple. Basically, right now we scrape example.html files for every scraper. But we don't verify that the output from the scrape is actually valid. 

This means that if a test doesn't return anything at all when scraping an example file, the test would pass, so long as no exception was raised. This is bad.

We should use the `to_json` method to make matching json files for every example file, and then add that to the tests. (Or do similar.)

**Comment by janderse** [comment]
Wasn't this fixed by bde8573df1de4eec5e7e1688274dd590f2371f07 ?  Is there anything more to do here?

**Comment by mlissner** [comment]
Good call, thanks!
