### ISSUE TITLE
installing in python3 bites it on wsgiref on OS X

### ISSUE THREAD

**Issue by eads** [freelawproject/juriscraper#184]
In a Python 3.6 virtualenv on OS X, I get this when pip installing:

```
Collecting wsgiref==0.1.2 (from juriscraper)
  Using cached wsgiref-0.1.2.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/vv/8g1xh6k11yv9tfcwf_f3r2h00000gp/T/pip-build-bvz9q_zo/wsgiref/setup.py", line 5, in <module>
        import ez_setup
      File "/private/var/folders/vv/8g1xh6k11yv9tfcwf_f3r2h00000gp/T/pip-build-bvz9q_zo/wsgiref/ez_setup/__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: Missing parentheses in call to 'print'
```

Fixed by using Python 2.7 instead.

**Comment by mlissner** [comment]
Sadly, I pulled Py3 support a few weeks ago:

https://github.com/freelawproject/juriscraper/commit/c7b6fef5b9e7177481542be7651ac35aa5571aa3

We had it briefly, but I pulled it when I dependency I needed didn't support it. I'd welcome figuring out how to get it back in, but if you read the git message above, you'll see that it doesn't feel like "our hill to die on."

(I just caught and fixed one more reference to it from the readme, sorry about this.)

**Comment by mlissner** [comment]
Feel free to re-open if you want to look into this. Weird that wsgi is a requirement though, and weirder that it fails Py3.

**Comment by eads** [comment]
All good -- I was rolling with Python3 since the README still said its supported. But I've seen these errors many times in my own code and know what to do :)

wsgiref seems to be a dependency of a lot of code that doesn't obviously need it, and I've never quite understood why.
