### ISSUE TITLE
Missing D.Mass 2014 cases? (e.g. Piccone v. Bartels)

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/juriscraper#186]
I hope this is the right place to file this sort of issue. (Lemme know if it should be filed under courtlistener instead?)

I chanced to notice that _Piccone v. Bartels, 40 F. Supp. 3d 198, 201-02 (D. Mass. 2014)_ is missing from CourtListener. that's `Case 3:11-cv-10143-MLW Document 76 Filed 08/25/14 Page 1 of 53` in D.Mass.

It appears in FDSYS at https://www.gpo.gov/fdsys/pkg/USCOURTS-mad-3_11-cv-10143/pdf/USCOURTS-mad-3_11-cv-10143-1.pdf

Since I'm under the impression that CL had scraped all recent opinions as of last month, I assume something's wrong. (I assume, also, that it has no way to know about the _F. Supp 3rd_ reporter, so the absence of https://www.courtlistener.com/c/F.%20Supp.%203d/40/186/ is not surprising.

**Comment by mlissner** [comment]
Interesting. Is this not it: https://www.courtlistener.com/docket/4965972/piccone-v-bartels/#entry-76

How were you searching for this?

**Comment by johnhawkinson** [comment]
That is indeed it. Per my seach history, I tried:

https://www.courtlistener.com/?q=PICCONE+v.+BARTELS&type=r&order_by=score+desc&party_name=Veritas
https://www.courtlistener.com/?q=Piccone+v.+Bartels&type=r&order_by=score+desc&party_name=Veritas
https://www.courtlistener.com/?q=11-cv-10143

Whoops. So, clearly the problem is somehow there was a lingering "Veritas" in the party name field in the first two queries. My bad! Properly amended, they do indeed find it:

https://www.courtlistener.com/?q=Piccone+v.+Bartels&type=r&order_by=score+desc
https://www.courtlistener.com/?q=PICCONE+v.+BARTELS&type=r&order_by=score+desc

but the third search (by docket #) does not! It finds the appellate case, but the district case.
Do you see something obvious I'm missing?

**Comment by johnhawkinson** [comment]
>  So, clearly the problem is somehow there was a lingering "Veritas" in the party name field in the first two queries. My bad! 

This really a CL issue not a JS issue, but looking at this, there are several UI issues:
<img width="1192" alt="screen shot 2017-09-08 at 00 54 54" src="https://user-images.githubusercontent.com/1270718/30196650-5e18ee56-9430-11e7-93b9-72009fcd88cf.png">

1. The left side search criteria don't fit on one screen, so it's easy to have stuff in the lower fields (Party, Atty name) that are affecting the search but not obviously.

2. The right side repeats the search criteria: "_Your search — Piccone v. Bartels — had no results._" but incompletely. It makes me think I don't need to worry about fields I can't see because it's telling me the search I did. But it's leaving out important information.

It's probably hard to fix 1, depending on design and mobile and resizing and all that. But 2 should be solvable. And the problem is bad really because of the combination of both. Fixing either of them would help. (But don't let me stop you from fixing 1)! :)

**Comment by mlissner** [comment]
The third query:

https://www.courtlistener.com/?q=11-cv-10143

Is against the opinions search because it lacks the `&type=r` param. If you add that back, it seems to work.

As for the UX issue, I don't know what we can do about inputs being off the screen. LOTS of sites have this problem, from Amazon to Kayak to Hotels.com. But you're right, it'd be nice if we could have a better error message. That's actually a bug we have in CourtListener: https://github.com/freelawproject/courtlistener/issues/716

Anyway, I'm going to close this issue since it seems like it was just an error in your search and since the rest of it is already going in https://github.com/freelawproject/courtlistener/issues/716. Feel free to reopen though if I missed something.
