### ISSUE TITLE
Scrape all ECF RSS feeds and incorporate them into RECAP database

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/juriscraper#195]
There are 173 ECF instances with RSS feeds, according to https://www.pacer.gov/psco/cgi-bin/links.pl
Most of them have a 24-hour lookback, and have varying scopes: some include all docket entries, others include only court orders, etc.

In any case, they provide information about newly filed information and docket metadata that should be incorporated into the RECAP database.

A scraper should run (ideally coincident with the ~20-minute update frequency of these feeds, but certainly no less than 2x/ the expiry frequency (24hrs/2 -> 12hours) to scrape all of this data.

It's not as great as scraping every docket, but it's free and it's quite helpful.

It also provides a rich set of associations between doc1 links, docket numbers, and case ids.

Example:
---

https://ecf.nysd.uscourts.gov/cgi-bin/rss_outside.pl

Southern District of New York - Recent Entries
Docket entries of type: adr,answer,appeal,appeal-cr,charge-cr,cmp,discov,discovery-cr,misc,misc-cr,misccs,mot2255,motion,notice,notice-cr,order,order-cr,respm,respm-cr,respoth,service,service-cr,transfer,transfer-cr,trial,trial-cr,waiver-cr

1:17-cv-08949 Martinez v. Commissioner of Social Security
November 18, 2017 at 11:56:35
[Civil Cover Sheet] (5)
1:17-cv-00723 Grynberg et al v. U.S. Department of Justice
November 18, 2017 at 11:46:35
[File Excess Pages] (54)
1:16-cv-09867 Erasmo Santos Salgado v. 2020 Deli Corp. et al
November 18, 2017 at 11:28:42
[Answer to Amended Complaint] (35)

```html
<item>
<title>1:17-cv-08949 Martinez v. Commissioner of Social Security</title>
<link>https://ecf.nysd.uscourts.gov/cgi-bin/DktRpt.pl?483944</link>
<description>[Civil Cover Sheet] (<a href="https://ecf.nysd.uscourts.gov/doc1/127121383781?caseid=483944&de_seq_num=25" >5</a>)</description>
<guid isPermaLink="true">https://ecf.nysd.uscourts.gov/cgi-bin/DktRpt.pl?483944&25</guid>
<pubDate>Sat, 18 Nov 2017 16:56:35 GMT</pubDate>
</item>

<item>
<title>1:17-cv-00723 Grynberg et al v. U.S. Department of Justice</title>
<link>https://ecf.nysd.uscourts.gov/cgi-bin/DktRpt.pl?468180</link>
<description>[File Excess Pages] (<a href="https://ecf.nysd.uscourts.gov/doc1/127121383778?caseid=468180&de_seq_num=152" >54</a>)</description>
<guid isPermaLink="true">https://ecf.nysd.uscourts.gov/cgi-bin/DktRpt.pl?468180&152</guid>
<pubDate>Sat, 18 Nov 2017 16:46:35 GMT</pubDate>
</item>
```

**Comment by mlissner** [comment]
This really is the next big source of data, I think. Thanks John.

The only tricky part is figuring out how to do this in a way that doesn't dilute the useful cases we already have in the archive. Any case gotten this way (which will quickly become the majority of cases, I suspect) will only have a limited set of metadata, and _no_ actual documents (or at least very few). If it becomes normal to do a search and have most of your responses go to a (nearly) empty docket, that might not be ideal. In a similar vein, as you're using RECAP, do you want to see links to these cases? I'm not entirely sure. Something to think about. Maybe it's fine.

**Comment by johnhawkinson** [comment]
> If it becomes normal to do a search and have most of your responses go to a (nearly) empty docket, that might not be ideal. 

Well, the "nearly empty" case is hard. The empty case is easily addressed with a checkbox in the search: "Include empty dockets?" I would tend to default it to TRUE but we could change it to FALSE with experience.

The obvious way to address "nearly" it to change the checkbox to a number: "Include dockets with less than **N** documents?" Not sure this is the best UI, but it's a place to start.


> In a similar vein, as you're using RECAP, do you want to see links to these cases? I'm not entirely sure. Something to think about. Maybe it's fine.

I don't see an issue with this one.

**Comment by mlissner** [comment]
I'm going to get started on this between the other work I'm doing. I think the two biggest questions I have are:

1. How often do we crawl an RSS feed, and how do we consistently identify what we've seen before? E.g., if we crawl once per hour, we'll be chugging through the feed and at a certain point we'll realize we already have the item we're looking at. How do we know to stop? Do I remember that sometimes they insert things in the middle?

2. How do we expose the contents of these feeds in the alerts UI given that the feeds seem to have different types of docket entries (`adr`, `answer`, `appeal`...)? I'd like to have something on every docket page where users can click to enable alerts. But when they do we need to make sure we set expectations correctly — if the court only provides answers, for example, we need to make sure the user knows that.

I guess feedparser is the tool for doing RSS stuff in Python? I've never done this before, but that's what I remember seeing people using.

**Comment by johnhawkinson** [comment]
I've done some thinking about this.

1: Ideally, you determine the update frequency and phase and you poll immediately after each update. I believe the CMECF RSS update frequency is 20 minutes (or was it 15?). So ideally your architecture has some tracking of this (crude PLL) and notice if the phase drifts. And of course, in a perfect world you'd supersample at 2x because Nyquist, but that's not necessary.

You should not trust feeds to be chronological. They are for the most part, but a backdated item or an unsealed item will appear in the middle, I believe.

Database lookups to track what you know already should not be expensive! If they are, your design should look at better hashing. And, of course, you really only need to track what-you-know in a rolling 24-hour window.

2: Is this an integrated alert architecture with email notifications and regular RECAP uploads? If so, well, even if a court only gives you docket type `xyz`, you can still generate an alert for `abc` if someone upload it  (setting aside for now non-numbered docket entries, so-called numbered minute orders, etc.).

Yes, feedparser ships with Python and parses RSS. It deals with the hairiness of inconsistent RSS time formats, and breaks out a feed into individual items. You should use it over rolling your own, but it doesn't break all that much to the table.

**Comment by mlissner** [comment]
Wow, keeping it simple, eh? I did some digging after I figured out what a PLL was, and found this:

https://www.xaprb.com/blog/2006/05/04/how-to-make-a-program-choose-an-optimal-polling-interval/

It's not bad, but it's not perfect either. It would be *really* nice to have some sort of auto-adjusting system that learns when to next download each court's RSS feed. That'd be pretty badass.

The other thing I'm not sure what to do with is how to actually schedule these things even if we have a good PLL kind of thing going. Should we use cron? Probably not — too fixed, but maybe we could trigger the thing every minute or so, and store the PLL delay somewhere such that whenever it's run, it either proceeds if the PLL delay is zero or is delayed by the PLL. This would sort of replicate the `at` command, I guess.

There's probably also a way to do this with celery, which lets you say, "Run this task in 20 minutes."

But questions:
 - How do we kick off the scrapers and then monitor that they're running? 
 - How do we avoid running the same scraper more than once at the same time if we've got cron jobs, for example, kicking things off every minute? 

I sense there's probably a better way to do all this.

**Comment by johnhawkinson** [comment]
I'm a little skeptical of your cited blog post (binary searches; it hearkens to TCP's additive increase, multiplicative decrease, but I think we know what's going on with more information than they do, so it's not necessary guess so blindly.)

But really I didn't mean you should handle this all for Day One. Rather, that you should choose an archiecture that does not preclude it.

> Should we use cron? Probably not — too fixed

Absolutely not. You should have a persistent process that has some idea of either interval scheduling or absolute time scheduling. As simple as, notionally:

```
while :; do get-the-feed; sleep 1200; done;
```

or something schnazzier.

> maybe we could trigger the thing every minute or s

This doesn't seem right, no.

I'm not educated on celery and can't speak to it.

> How do we kick off the scrapers and then monitor that they're running?

I mean, clearly there's a schedule process that handles this and perhaps deals with distributing them across hosts and processes if that were actually necessary.

> How do we avoid running the same scraper more than once at the same time if we've got cron jobs, for example, kicking things off every minute?

Well, we won't, but that's what the scheduler abstraction is for.

**Comment by mlissner** [comment]
I guess there's two ways to handle the daemonization part of this. Making true and real daemons is a pain: You have to do things to make them work in the OS, and they get installed into the OS at some point, and blah, they're just messy at least with the set up we've got currently. I always regret going down that path. It's also a pain to get them to interact with Django properly (how do they get access to Django's settings, etc).

So...I think what I'll do is write up a Django management command and have it get started via an ~hourly cron job. In theory, I can design it to run forever and to only allow one instance to be run. So the cron job would just be to make sure it's running and restart it if it crashes — which it inevitably will, for a while, anyway.

With that in place, figuring out the timing thing should be doable in Python/Django which should be nice. I think the way it could work is that scheduling could be handled in the management script, and then downloading and parsing could be handled via celery tasks. That'd give it a nice distributed architecture for the actual work, and a centralized one for the work management.

A question: How confident are you about update intervals of these RSS feeds? If they're intervals, maybe the trick is to try to just figure out the average update period, and to then use that to schedule our next download. Hm. The download task could also be configured with a retry mechanism for one minute later if it doesn't detect get any changes, just in case it's fired a tad too early.

**Comment by mlissner** [comment]
Also found this. Not super helpful, but it seems to be good guidance re polling RSS: https://stackoverflow.com/questions/939642/policy-for-polling-rss

**Comment by johnhawkinson** [comment]
> So...I think what I'll do is write up a Django management command and have it get started via an ~hourly cron job. 

This is a **really bad idea**.
It's the wrong archiecture, it's going to force you into bad decisions, and it's going not going to perform well.

**Comment by mlissner** [comment]
Can you please elaborate? How is it different than running a script as a daemon? The advantages I see are:

 - OS independent (init scripts vs. whatever the hotness is these days for daemons)
 - Access to Django utils, settings, and database
 - Python

**Comment by mlissner** [comment]
I did a big part of this over the past day or two. The general architecture so far, is to do it as a django management command that simply runs forever. As it runs, it iterates over all the PACER courts with RSS feeds. For each court, it checks if it has been run in the past five minutes. If so, it moves on. If not, it downloads the feed and checks the value in the `lastBuiltDate` field vs. the value that was found the last time that court was run.

If the value has changed, we process the entire feed, adding it all to the database and search engine, and then finally, marking the court as updated.

The biggest problem I see with this right now is that it is going to be absolute murder on our performance. For example, many of these feeds have hundreds or even thousands of items. The one with the most items right now has about 3,000 items. But even if we figure that they only have 500 on average, each, that's 500 items × 200 feeds = 100,000 items. That's...not good. 

I think the next step before I deploy this will be to add some form of early aborting code, sort of like how we have in our other scrapers. I think we just need to make some assumptions about what's new and what's old, and stop once we hit stuff we've seen before. If it means that we sometimes miss something that's entered into the middle of a feed, I think that's probably OK. Maybe we do a full check of the whole feed once/night or something just to be sure.

**Comment by johnhawkinson** [comment]
_mlissner commented "2018-04-18T22:50:10Z" (Apr 18, 2018, 6:50 PM EDT")_

> Can you please elaborate? How is it different than running a script as a daemon? The advantages I see are:  • OS independent (init scripts vs. whatever the hotness is these days for daemons); • Access to Django utils, settings, and database; •  Python

Sorry, I've been distracted. I wanted to get myself on the record before you started, and had intended to elaborate within a few hours. But hours turned to days, days turned to weeks, and here we are.

I should break out my concern. It's not so much that it is a bad idea to have it as a Django command, but it's bad idea to have an architecture that is predicated on _hourly_ anything.

This is a continuous monitoring process and it calls for a persistent process, whether one per court or one overall I don't know. There are tools to monitor long-running processes and ensure they are still running, like djb's "supervise" (daemontools) or "runit" or I guess "systemd."  There's probably more modern stuff on this (mumble celery). And maybe you didn't really mean "hourly" as much as "there should be a periodic background task that handles supervision."

Now to see what you have wrought…

**Comment by johnhawkinson** [comment]
In https://github.com/freelawproject/courtlistener/commit/0d0c9d493bf99b3d2853b710ebabee4e6b79bb8a you define the model thus:

https://github.com/freelawproject/courtlistener/blob/0d0c9d493bf99b3d2853b710ebabee4e6b79bb8a/cl/recap_rss/migrations/0001_add_rss_feed_models.py#L14-L24

I think you should be tracking more here.
I would be tracking the presumptive update interval (e.g. current `lastBuildDate` minus the previous).
I realize your `PacerRssFeed` class has a `url` method, but I think you should preserve the actual URL used, and have a plan for redirects. For instance, it's worth tracking this stuff:

```
pb3:courtlistener jhawk$ curl -I  'https://ecf.nyed.uscourts.gov/cgi-bin/rss_outside.pl'
HTTP/1.1 302 Found
Date: Tue, 01 May 2018 20:55:42 GMT
Server: Apache
Location: https://ecf.nyed.uscourts.gov/cgi-bin/readyDockets.pl
Cache-Control: max-age=0
Expires: Tue, 01 May 2018 20:55:42 GMT
Connection: close
Content-Type: text/html; charset=iso-8859-1
``` 

because it may inform you later and assist with diagnostics.

And, of course, if you're not tracking the interval, you can't make use of it to Be Smart(tm).

**Comment by johnhawkinson** [comment]
> That's pretty much where it landed. One thing will run constantly with its own timers built in, and if it crashes, another thing will start it back up again (probably via cron).

Cron is definitely wrong for this. You do not have a periodic process. Trying to shoehorn cron into managing continuous processes works poorly. You want something that watches your process and notices when it dies. There is no reason that should not be a triggered instantaneous notification from thekernel, rather than a poor man's hourly poll.

> Doing it now would just add complexity that I'd not want in the future.

It's good to design the API in advance. That doesn't preclude adding things later. I realize we're past "advance." But leaving good stuff for later to add in isn't a great way to design. It leads to ad hoc-ery.

> That'd...be...not very useful since it's easy to lookup on pacer.gov or in the code

Well, I mean other than what is on pacer.gov, which isn't authoritative.
As for redirects, I refer to their historical value. You want to know if is broken now and was redirecting elsewhere last week and it stopped.

**Comment by johnhawkinson** [comment]
Making my way into the code, I didn't get very far before running across:

https://github.com/freelawproject/courtlistener/blob/03d03ee57d7d9a244584c606810eeb81f0482900/cl/recap_rss/tasks.py?utf8=%E2%9C%93#L18-L22

```.py
def get_last_build_date(xml_string):
    """Get the last build date for an RSS feed"""
    doc = lxml.etree.fromstring(xml_string)
    last_build_date_str = doc.xpath('//lastBuildDate/text()')[0]
    return parser.parse(last_build_date_str, fuzzy=False)
```

Yikes!

This is a big abstraction violation. This code generally uses `feedparser` to parse the feeds, so you should not be parsing the feed itself with your own XML without a really good reason, and that really good reason should be documented in the code.

After some discussion, it appears that the reason is that `feedparser.parse()` on a big feed can take 2 or 3 seconds to run (in addition to the HTTP retrieval time), and the current archiecture polls more frequently than the feeds update (5 minute polls; some feeds update hourly or slower) and it's desirable to discard unchanged feeds without running the resource-intensive parser.

So instead the URL is retrieved with `requests` and then parsed with a hand-rolled lxml parser (Above), and only if the date is updated is it then parsed with `feedparser`.

This is not how you're supposed to use feedparser, and it introduces a lot of issues. They should all be documented in comments in the code, at a minimum. Some of this is documented in `check_if_feed_changed`, but not enough.

Using `requests` means you are not using the `ETag` and `Last-Modified`/`If-Modified_Since` headers, and both of them are basically a requirement for well-behaved RSS readers. Not using them is being a bad network citizen, and is not acceptable for a large project. And of course, `feedparser` would handle them automatically. Somewhat mitigating is that CMECF does not at present support either of them, so one could argue that nothing is lost. But of course, when CMECF is upgraded to support them, most RSS clients will immediately do the right thing, but juriscraper won't, and that's really bad. Needs attention!

On the flipside, one of MIke's reasons for using `requests` is to ensure timeouts are reasonable and also that exceptions are properly handled. I'm confident that exceptions can be handled ad hoc (you'll know when you catch one!), or with logging, and as for timeouts, `feedparser` calls `urllib2` which honors  [socket.setdefaulttimeout](https://docs.python.org/2/library/socket.html?highlight=socket#socket.setdefaulttimeout), so that's a solution.

But it doesn't solve the parsing overhead problem.

So we're kind of stuck.

In some informal benchmarks, the `lxml` parser runs about 1000x faster than `feedparser`:

```
>>> timeit.timeit("f2.feed.date", setup="import feedparser; f2= feedparser.parse('https://ecf.nyed.uscourts.gov/cgi-bin/rss_outside.pl')", number=1)
6.9141387939453125e-06
>>> timeit.timeit("f2.feed.date", setup="import feedparser; f2= feedparser.parse('https://ecf.nyed.uscourts.gov/cgi-bin/rss_outside.pl')", number=10)
3.409385681152344e-05
```

```
>>> r = s.get('https://ecf.nysd.uscourts.gov/cgi-bin/rss_outside.pl')
>>> t1=datetime.now(); d=lxml.etree.fromstring(r.content); print d.xpath('//lastBuildDate/text()')[0]; t2=datetime.now(); print t2-t1;
Tue, 01 May 2018 23:05:59 GMT
0:00:00.031799
```

But on the other hand, lxml is not exactly fast here either. A regexp is another 1000x faster:

```
>>> t1=datetime.now(); m=re.search(r'<lastBuildDate>(.*)</lastBuildDate>', r.content); t2=datetime.now(); print t2-t1;
0:00:00.000294
>>> print m.groups(1)
('Tue, 01 May 2018 23:20:01 GMT',)
```

Also, there is some irony, the code claims it is using a regexp:
https://github.com/freelawproject/courtlistener/blob/03d03ee57d7d9a244584c606810eeb81f0482900/cl/recap_rss/tasks.py?utf8=%E2%9C%93#L55-L57

```
    One other oddity here is that we use regex parsing to grab the
    lastBuildDate value. This is because parsing the feed properly can take
    several seconds for a big feed.
```

---

So, I would suggest switching this to a regexp for now, and carefully noting all the problems that arise from using requests over `feedparse`r. Maybe filing some `feedparser` issues too.

**Comment by johnhawkinson** [comment]
I've put comments on commits:
https://github.com/freelawproject/courtlistener/commit/03d03ee57d7d9a244584c606810eeb81f0482900#r28816164
https://github.com/freelawproject/courtlistener/commit/c83b4c7f1ca784f26522258025b5ebaa495670e1#r28816188
https://github.com/freelawproject/courtlistener/commit/c83b4c7f1ca784f26522258025b5ebaa495670e1#r28816168
https://github.com/freelawproject/courtlistener/commit/ddee90106415a62f494a53e68f53bc9f9e383d3a#r28816213
https://github.com/freelawproject/courtlistener/commit/ddee90106415a62f494a53e68f53bc9f9e383d3a#r28816226


I do feel particularly guilty for articulating what are architecural/design comments a fortnight ago. :(
Sorry.

**Comment by johnhawkinson** [comment]
Over in juriscraper:

```patch
+As of 2018-04-25, these jurisdictions do not have functional RSS feeds:
+
+'miwb', 'nceb', 'nmib', 'alnd', 'caed', 'flnd', 'gand', 'gasd', 'hid', 'ilsd',
+'kyed', 'mdd', 'msnd', 'mtd', 'nvd', 'nywd', 'ndd', 'oked', 'oknd', 'pamd',
+'scd', 'tnwd', 'txnd', 'vaed'
```

If we had an architecture that better handled polling intervals, we would poll these districts infrequently (once a day?) checking for a feed to see when it gets turned on.

Also, I'd like to see a commandline driver to process XML from stdin, like for `DktRpt.pl`.
In retrospect I think it was silly to do this as a separate file (`pacerdocket.py`), and instead `pacer/rss_feeds.py` should just check `if __name__ == "__main__"` in the standard Python idiom.

How about Appellate RSS support?

I think that's about it for my comments. Sorry to be so longwinded.

**Comment by mlissner** [comment]
> So, I would suggest switching this to a regexp for now, and carefully noting all the problems that arise 

Done in freelawproject/courtlistener@84c5ec3853a2561760de5c804c33e4dd2cbacb77

> pacer/rss_feeds.py should just check if name == "main" in the standard Python idiom.

Done in freelawproject/juriscraper@b5e47439c75540125f1579389f2cf2bdd295d0ba

**Comment by mlissner** [comment]
This is...effectively done. Issues will arise, but they get their own home, elsewhere. WOO! The firehose has begun. So far today we've got upwards of 50k new documents. Today.
