### ISSUE TITLE
Massachusetts appellate URL change

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/juriscraper#196]
Mass. has restructued its website as of a month or so ago, and new opinions are not being scraped.

It moved opinions from
  http://www.mass.gov/courts/court-info/sjc/about/reporter-of-decisions/new-opinions.html
to
  https://www.mass.gov/service-details/new-opinions.

Juriscraper was using an XML (RSS?) variant of the first page:
  http://www.mass.gov/courts/court-info/sjc/about/reporter-of-decisions/opinions.xml

https://github.com/freelawproject/juriscraper/blob/67dfee19e219cbf1f277b439ce2342c7bb68f53f/juriscraper/opinions/united_states/state/mass.py#L27

I don't know if that still exists at a new URL.

Note that some of this kinda lost to history forever because Mass slip opinions disappear after 14 days. They can be obtained via the free LEXIS site, but that formats them differently.

**Comment by mlissner** [comment]
@arderyp Have you looked into this / noticed this?

**Comment by arderyp** [comment]
yes @mlissner. Below is excerpt form Slack.  I haven't committed anything... waiting on your go-ahead:

```
Philip Ardery [7:05 PM] 
@mike and @jhawk, I am going to push a fix for the Mass scraper regarding the issue recently opened.  @mike, I'll be ditching the old test files, since the site uses a new structure.  The old string parsing test cases remain, however.  I don't see an xml endpoint for the new page, so my changes are for parsing the raw HTML page that @jhawk referenced.

@mike, this scraper was originally parsing the date from the link text, then we started using the 'published' field from the XML when we started seeing recurring issues where the court was not including a date in the link text.  Since we don't have xml published field to rely on anymore, I've updated the base xpath to require '<current year>)' in the link text.  This means we will miss some things, but the only alternative it to email Mass every time there is an issue.  There is currently a missing date issue on the HTML page right now, and it looks like this is somewhat common.

It's less than ideal.

Let me know if you'd like me to proceed.


[7:07] 
also, @mike, my simplified regex may be too loose (not explicitly restrictive enough for our tastes), but the old regex was difficult for me to wrap my head around... I was struggling to debug it
```

**Comment by arderyp** [comment]
@mlissner I also send an email with you CC'd to a guy named Isaac Wilhelm.  Isaac suggested they were going to create a new RSS feed... I've been prodding him to see when that might be. If it is not for the foreseeable future, we can implement the workaround code I've got for parsing their new HTML page.  I can push that workaround code whenever you give me the green light.
