### ISSUE TITLE
PACER written opinion report scraper broke this month

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/juriscraper#199]
Apparently sometime on or after Nov. 3, if the written opinion report for `ecf.mad` is to be believed:

<img width="769" alt="screen shot 2017-11-18 at 15 17 24" src="https://user-images.githubusercontent.com/1270718/32984392-c35d9a3e-cc73-11e7-8923-9c861d6f473f.png">

(going by the lack of blue [R] icons.)

**Comment by mlissner** [comment]
This is now fixed. We just uploaded 50-60k documents to the Internet Archive.
