### ISSUE TITLE
Some parties don't get a `type` field when parsed

### ISSUE THREAD

**Issue by mlissner** [freelawproject/juriscraper#209]
Usually the type field says "Defendant" or "Plaintiff" or whatever, but alas, some parties don't get this field populated. That *might* be fine (?), but CourtListener assumes this field always has a value, and when it doesn't, CourtListener barfs and doesn't add the associated attorneys for that party.

That's one way that freelawproject/courtlistener#761 is happening, but I think there's another way too, that I'll track that down in that bug.

**Comment by mlissner** [comment]
Here's an example html file from pq 229090:

[ilnd_310470.txt](https://github.com/freelawproject/juriscraper/files/1742466/ilnd_310470.txt)

I got the crashing email from this one.

**Comment by johnhawkinson** [comment]
Err, that's because "Service List" isn't a party. It's another special case... (I think we see this in bankruptcy, too?)

Unless you don't mean "Service List," in which case…which part of `ildn_310470` are you referring to?

**Comment by mlissner** [comment]
Yep, service list it is. You nailed it.
