### ISSUE TITLE
Issue with Install

### ISSUE THREAD

**Issue by starkemc** [freelawproject/juriscraper#212]
I am using Windows 10 and I am trying to follow the instructions (I am a developer but very new to python)  when trying run pip install juriscraper I receive the following error..   Any ideas ?

PS C:\Users\Mike\Desktop\juriscraper-master\juriscraper> pip install juriscraper
Collecting juriscraper
  Using cached https://files.pythonhosted.org/packages/bc/25/a0a230c9be880e4bd45a07f2d6866728b3e65c6000aa5cacbd75407aeb47/juriscraper-1.1.0.tar.gz
Collecting argparse==1.2.1 (from juriscraper)
  Using cached https://files.pythonhosted.org/packages/6f/ad/86448942ad49c5fe05bfdf7ebc874807f521dfcca5ee543afaca2974ad5a/argparse-1.2.1.tar.gz
Collecting cchardet (from juriscraper)
  Using cached https://files.pythonhosted.org/packages/ad/33/216ad3ba6f7982be3f9895bc9059c6b4a769e9522b3656c8ad87e7a49fdf/cchardet-2.1.1-cp36-cp36m-win_amd64.whl
Collecting certifi (from juriscraper)
  Using cached https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl
Collecting chardet (from juriscraper)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting geonamescache==0.20 (from juriscraper)
  Using cached https://files.pythonhosted.org/packages/b1/96/c0d710f45ea3eea82ad96db71b20da49000e2519d637b6f6beb9a785c610/geonamescache-0.20.tar.gz
Collecting lxml==3.5.0 (from juriscraper)
  Using cached https://files.pythonhosted.org/packages/8b/be/ed850baac891aca25c832fb8d7b9c0e7a5077a30e336d95ffc7d649aaa06/lxml-3.5.0.tar.gz
Collecting python-dateutil==2.5.0 (from juriscraper)
  Using cached https://files.pythonhosted.org/packages/b2/2c/1e76d08cbfb4d81faa4ab9995ed5d3ac45bd380da32df1733530dfdd8123/python_dateutil-2.5.0-py2.py3-none-any.whl
Collecting requests==2.2.1 (from juriscraper)
  Using cached https://files.pythonhosted.org/packages/7d/15/6efffc6aee666e1456852c2bf1d483b46bf971a2d509b35a98fc3eae1c60/requests-2.2.1-py2.py3-none-any.whl
Collecting selenium==2.43.0 (from juriscraper)
  Using cached https://files.pythonhosted.org/packages/34/64/be80da5426c1edb06399632c0d3fe3cd370c0f3b045e5249cec53c233c13/selenium-2.43.0.tar.gz
Collecting wsgiref==0.1.2 (from juriscraper)
  Using cached https://files.pythonhosted.org/packages/41/9e/309259ce8dff8c596e8c26df86dbc4e848b9249fd36797fd60be456f03fc/wsgiref-0.1.2.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Mike\AppData\Local\Temp\pip-build-ekifqjmx\wsgiref\setup.py", line 5, in <module>
        import ez_setup
      File "C:\Users\Mike\AppData\Local\Temp\pip-build-ekifqjmx\wsgiref\ez_setup\__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Setuptools version",version,"or greater has been installed.")?

**Comment by mlissner** [comment]
Are you trying to install this on Python 3? Unfortunately, that's not supported.

**Comment by starkemc** [comment]
awesome, thanks I will give that a try... nice work!!  Impressive stuff!

**Comment by mlissner** [comment]
Sorry about that. We had it working briefly, but there were some crazy bugs that were more work than it was worth to fix.
