### ISSUE TITLE
back scrape iterable

### ISSUE THREAD

**Issue by umeboshi2** [freelawproject/juriscraper#240]
I managed to find some free time to work with these projects.  I started the freelawmachine and ran the back scraper for both ```miss``` and ```missctapp```.  I noticed that the years were not letting me perform a complete scrape in 2018.  The way vagrant works, it was easy to just place my juriscraper fork in the ```/vagrant``` directory and ```pip install``` it with the changes I needed.  However, those changes use "magic year numbers."

How do y'all want to identify the years that are back scrapable?  I feel that the beginning year should be "hardcoded" since each state is different and may only be scraped back to when the state started maintaining an online presence.  For the end year, I'm thinking about a PR using ```datetime.now().year``` or ```year  - 1```.  If one of these is acceptable, should I add a ```current_year``` property to the ```OpinionSite``` class to make the code a bit more dry?

https://github.com/freelawproject/juriscraper/blob/6ee205d694f253e036de4feec885f083bb76ffc0/juriscraper/opinions/united_states/state/missctapp.py#L21

https://github.com/freelawproject/juriscraper/blob/6ee205d694f253e036de4feec885f083bb76ffc0/juriscraper/opinions/united_states/state/miss.py#L18

**Comment by mlissner** [comment]
Thanks for filing this, but I'm not sure I care, tbh. There's a tradeoff here between two mentalities:

1. `back_scrape_iterable` represents things we *know* work, and so should be hardcoded.

2. It tries to always be up to date.

I *think* I prefer the former since the backscrapers are typically used pretty rarely and there's some understanding that you might need to carefully look at what it's doing before you run it. But like I say, I'm not sure I care? It's a pretty seldomly used feature.

**Comment by umeboshi2** [comment]
Yes, the "up to date" part is why I referenced the two MS appellate iterables.  Running both the regular scraper and backscraper on both courts seems to ignore a few years worth of cases.

Also, since you mention that it's a seldomly used feature, I was curious what the normal use actually is.  My use has been to build a more local subset of data from Mississippi, fifth circuit, and MS districts, while only gathering outside data as cited in the opinions from this subset.  What do other people use the code for?

I hope you had a Merry Christmas! :)

**Comment by mlissner** [comment]
It's mostly a one-off tool, actually. We use it the first time we create a scraper if a website has easily scrapable historical content. In that case, we set up the backscrape iterable, run it on the server to get the content and then clean our hands of it. 

Once in a while somebody wants this data and we recommend they either get it from our APIs or update the code (typically).

**Comment by umeboshi2** [comment]
Since it is a one-off tool, and since beautifulsoup4 is already in courtlistener, and also since the ```Site``` metaclasses don't appear to directly depend on ```xpath```, would it be permissible to include bs4 in the requirements and allow developers to create scrapers using whichever tool that they are more comfortable using?

**Comment by mlissner** [comment]
I've resisted in the past. The main reason being that maintenance is easier
if we only use one tool and all scrapers look more or less the same. I also
find that XPath forces you to write what you intend more clearly while BS
lends itself towards writing `some_node.next().next().next()`, which is
horrible later.

BS4 is in CourtListener, but I think it's a legacy dependency. I can't
think of anywhere that it's actually *used*.

**Comment by umeboshi2** [comment]
Understood.  I don't use BS in the manner you mentioned, but mostly use selectors.  I found a nice [cheatsheet](https://devhints.io/xpath) that will help me convert selectors into spath expressions.  I also couldn't find it being used in courtlistener.

I used robobrowser to scrape the oral arguments from miss and missctapp (late 2013 to present).  The pages that are addressable by year link to the sittings, and each sittings page holds the oral arguments for that sitting.  To scrape the oral arguments for a certain year, the scraper must also parse the intermediate page that lists the sittings.  What's the best way to do this using the provided scrapers?

**Comment by mlissner** [comment]
Intermediate pages aren't our prettiest thing, but take a look here for an example:

https://github.com/freelawproject/juriscraper/blob/5ef3340318e6da56c953330d3967e2cb242e277f/juriscraper/opinions/united_states_backscrapers/state/nd.py#L21-L44

Basic idea is that we use a `DeferringList` object instead of a list. The difference between the two is that DeferringList object has a "fetcher" that runs the first time any item in the list is accessed. So when you do:

    a = DeferringList(fetcher=some_function, seed=some_list)
    item = a[0]

It'll run `some_function` with `some_list[0]` as its argument. `some_function` can then go do whatever is needed to get some other page and return the result.

**Comment by umeboshi2** [comment]
Yes, it will take me a little while to wrap my head around that.  Also, if you are interested in scraping .wpd files, it seems that Mississippi appellates have .wpd files (in a zip archive) in the hand down lists, which are accessible from the opinion lists that are already being scraped.

**Comment by mlissner** [comment]
wpd in zip is just on the other side of the line where we don't have tools to do useful things. In any case, can we close this one down?

**Comment by umeboshi2** [comment]
Yes.  Do you want to leave the back_scrape_iterables for miss and missctapp as they presently exist?  Since there are six sittings per year here, when I create the oral-args scraper, should I make the back_scrape_iterable a list of tuples of the form (year, sitting number) to bypass having to parse intermediate pages?

**Comment by mlissner** [comment]
> Do you want to leave the back_scrape_iterables for miss and missctapp as they presently exist?

Either way. If it helps you to update them, by all means. 

> Since there are six sittings per year here, when I create the oral-args scraper, should I make the back_scrape_iterable a list of tuples of the form (year, sitting number) to bypass having to parse intermediate pages?

Doesn't matter too much to me, provided we can achieve the goal of parsing the pages. Really, whatever is easiest is probably fine?

**Comment by umeboshi2** [comment]
Ok, I'll take the path of least resistance.  Thanks! :)
