### ISSUE TITLE
9th Circuit Scraper Missed Some Unpublished Opinions

### ISSUE THREAD

**Issue by brianwc** [freelawproject/juriscraper#256]
At least some unpublished 9th Circuit opinions from 06/29/2011 appear to be missing from the archive.

This one, the first one, from the same day is there: [ALICIA AGUILAR V. ERIC H. HOLDER JR.](https://www.courtlistener.com/opinion/220006/alicia-aguilar-v-eric-h-holder-jr/) but it appears that every other unpublished 9th Cir. opinion from that day is missing.

I do not know if this sort of error occurred on other nearby days. It's conceivable we only got the first opinion on the page for a long period of time, not just this one day. Someone should check.

**Comment by mlissner** [comment]
This will likely have to happen after we do our audit of published content, but I think that should be starting pretty soon.

**Comment by brianwc** [comment]
I take it all back. Somehow it now appears that all of them are there. I think I'm lousy at searching or there's something odd about the title of the case I was looking for that was making it not come up.
