### ISSUE TITLE
CI Failing on PACER Tests: Should we isolate all network tests?

### ISSUE THREAD

**Issue by arderyp** [freelawproject/juriscraper#263]
CI builds have been failing consistently and releases haven't been distributed to PYPI because of failing PACER tests that run over the network.

For other projects I've worked on that benefit from having tests executed over the live network, I've isolated those network tests so that they don't run by default.  They only run when I pass a specific command line argument, which I do on demand, in dev, whenever I deem it necessary.  

Should we implement this here?  I think all network tests should be isolated and releases should not depend on them passing.  Maybe after all non-network tests pass, we could cut the release build, then run the network tests just for good measure.  That way Circle would tell us when network tests were failing, but our release builds wouldn't be rejected as a result.

I think this is worth considering because failing PACER tests have become a rather common issue and its getting pretty annoying.

```
======================================================================
ERROR: test_queries (tests.test_pacer.PacerDocketReportTest)
Do a variety of queries work?
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/circleci/repo/tests/test_pacer.py", line 718, in test_queries
    self.report.query(self.pacer_case_id)
  File "/home/circleci/repo/juriscraper/pacer/docket_report.py", line 940, in query
    data=query_params)
  File "/home/circleci/repo/juriscraper/pacer/http.py", line 122, in post
    r = super(PacerSession, self).post(url, **kwargs)
  File "/home/circleci/repo/venv/lib/python2.7/site-packages/requests/sessions.py", line 572, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/circleci/repo/venv/lib/python2.7/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/circleci/repo/venv/lib/python2.7/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/home/circleci/repo/venv/lib/python2.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
SSLError: HTTPSConnectionPool(host='ecf.cand.uscourts.gov', port=443): Max retries exceeded with url: /cgi-bin/DktRpt.pl?1-L_1_0-1 (Caused by SSLError(SSLError(1, u'[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:727)'),))

======================================================================
ERROR: test_using_same_report_twice (tests.test_pacer.PacerDocketReportTest)
Do the caches get properly nuked between runs?
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/circleci/repo/tests/test_pacer.py", line 768, in test_using_same_report_twice
    self.report.query(self.pacer_case_id)
  File "/home/circleci/repo/juriscraper/pacer/docket_report.py", line 940, in query
    data=query_params)
  File "/home/circleci/repo/juriscraper/pacer/http.py", line 122, in post
    r = super(PacerSession, self).post(url, **kwargs)
  File "/home/circleci/repo/venv/lib/python2.7/site-packages/requests/sessions.py", line 572, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/circleci/repo/venv/lib/python2.7/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/circleci/repo/venv/lib/python2.7/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/home/circleci/repo/venv/lib/python2.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
SSLError: HTTPSConnectionPool(host='ecf.cand.uscourts.gov', port=443): Max retries exceeded with url: /cgi-bin/DktRpt.pl?1-L_1_0-1 (Caused by SSLError(SSLError(1, u'[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:727)'),))

----------------------------------------------------------------------
```

**Comment by johnhawkinson** [comment]
We should also work to have these tests run against our own (faux) server, rather than an AOUSC server. Although that might imply we should do other kinds of monitoring against CMECF to catch unexpected interface changes.

**Comment by arderyp** [comment]
I'm not hip enough to the lingo to understand your comment fully @johnhawkinson, but testing over the network against our own servers instead of external (PACER, or other) servers sounds like a more stable testing approach if it's doable.  That being said, I am not sure what this would entail, how we'd spoof the responses, etc.  My thoughts go immediately to @mlissner's VCR approach, but as I recall we had to scrap that for some reason...

**Comment by mlissner** [comment]
Yeah, let's skip all the network tests on CircleCI. Think you're up for making these changes, @arderyp ?

**Comment by arderyp** [comment]
Can you provide a list of all test (that you know of) that hit the network @mlissner

**Comment by mlissner** [comment]
Hm. Not really, actually. There ought to be a good trick for this though. Like, here's one option, that'll throw an exception when the test runs. I suppose you could modify it to do a log line?

https://stackoverflow.com/a/18601897/64911

**Comment by arderyp** [comment]
Interesting.  I suppose I could also just cut my WiFi connection and see what barfs.  But, maybe disallowing network connections during default test runs is a good protocol, as it will throw a red flag to people developing new scrapers if their test is hitting the network unexpectedly.

**Comment by mlissner** [comment]
> Interesting. I suppose I could also just cut my WiFi connection and see what barfs. 

Yeah, could totally work, I think. 

> But, maybe disallowing network connections during default test runs is a good protocol, as it will throw a red flag to people developing new scrapers if their test is hitting the network unexpectedly.

I think I support this in theory, but it's probably painful to get right in practice and maybe not worth the time to do with code (and instead is worth doing with practice/code review/etc.)

**Comment by arderyp** [comment]
@mlissner this is going to be a somewhat big ordeal, I think.  But, it's long overdue and worth pursuing.  

Firstly, there are a number of scraper tests that hit the network.  I am in the process of weeding them out--I will update the table below accordingly.  

Secondly, I have no PACER accounts or configuration, so I cannot say for sure which pacer tests are (not) hitting the network (excepting those listed below).  So, I need _you_ to run the test suite with WiFi disabled on your machine too weed those out and update the table below.

Scraper Tests Hitting Network
---
`juriscraper/opinions/united_states/federal_special/ag.py`
...

PACER Tests Hitting Network
---
`tests.test_pacer.PacerAuthTest::test_logging_in_bad_credentials`
`tests.test_pacer.PacerAuthTest::test_logging_short_password`
`tests.test_pacer.PacerAuthTest::test_logging_short_username`
...

**Comment by mlissner** [comment]
Here are my results. It's an HTML file, which should make this easy.
[Test Results.zip](https://github.com/freelawproject/juriscraper/files/3433066/Test.Results.zip)

**Comment by arderyp** [comment]
great @mlissner, thats basically the same list I came up with.

So I've made some major changes to the testing suite, most notable test isolation, test grouping, and the method of running tests.

I've changed the testing structure from our current structure:

```
tests/
  examples/
  test_everything
  test_pacer
```

to the following:

```
tests/
  examples/
  local/
    __init__.py
    PacerParseTestCase.py
    test_DateTest.py
    test_DocketParseTest.py
    test_JudgeParsingTest.py
    test_PacerNeedLoginTest.py
    test_PacerParseAppellateDocketTest.py
    test_PacerParseAttachmentPageTest.py
    test_PacerParseCaseQueryAdvancedBankruptcyTest.py
    test_PacerParseCaseQueryTest.py
    test_PacerParseDocketHistoryReportTest.py
    test_PacerParseInternetArchiveReportTest.py
    test_PacerParseRssFeedTest.py
    test_PacerPossibleCaseNumbersTest.py
    test_PacerUtilTest.py
    test_ScraperExampleTest.py
    test_ScraperSpotTest.py
    test_StringUtilTest.py

  network/
    __init__.py
    test_PacerAuthTest.py
    test_PacerDocketReportTest.py
    test_PacerFreeOpinionsTest.py
    test_PacerSessionTest.py
    test_PacerShowCaseDocApiTest.py
```

As your report shows, there are a couple test methods in a few of the "network" test classes that don't hit the network.  I don't have the energy to seperate those out, and these seem logically coupled, so I figured it would be fine to leave the structure as is above.

Also, I figured out how to run the "local" and "network" tests in isolation:

```
run local tests with:    python -m unittest discover -s tests/local -v
run network tests with:  python -m unittest discover -s tests/network -v
```

I update README to reflect this, and I changed `setup.py` to indicate this information when someone runs `python setup.py test` (which no longer does anything).

I tried for a while, but coudn't manage to make the isolation work smoothly with `python setup.py test`, is this a problem?  I would just have CircleCI call the seperate commands above where appropriate.

Since this is kind of complex, I was planning to submit a PR and bump the middle version number.

@mlissner thoughts?

**Comment by arderyp** [comment]
well, now seeing the issue with tox, which depends on `python setup.py test`...  interested to hear your thoughts

**Comment by arderyp** [comment]
@mlissner , well, I've got it setup now so that `python setup.py test` runs _all_ tests, which means tox works again.  The isolated grouping commands I posted above still work though, and I think those are what we'd call in circle.  Does that sound reasonable?  We were never calling `tox` in circle (not sure about Travis).

I'd really rather `python setup.py` execute the "local" tests only, but haven't quite figured out how to do that.  Will keep looking.

**Comment by mlissner** [comment]
Hm. Something isn't quite right about #267 now that it's hitting CircleCI. Can you explain what's *supposed* to be happening? I just pushed a non-tagged commit (the merge commit), and it failed due to network tests, and I pushed a tagged commit, which also failed due to network tests. I thought we were eliminating network tests from the automated suite?

**Comment by arderyp** [comment]
we dont want to eliminate them altogether.  We want to run them, we just dont want to make a build dependent on them.  I will keep looking into this.  I knew there were issues with Circle, but these specific issues are new to me.

**Comment by arderyp** [comment]
@mlissner your latest commit passed on `build-test-network` and failed to complete `build-test-all` and `build-test`.

I am now even more confused because the original problem I was witnessing was that the PACER_* env variables weren't working in Circle, but your latest `build-test-network` appears to suggests that they _did_ work there.  I need to dig into these Circle logs.  For now, please stop committing.

**Comment by arderyp** [comment]
@mlissner, I've got a stopgap measure in place.  The lastest code is now out on PYPi (1.25.1).

My remaining question @mlissner is this... do we want to run network tests in CI for commits to master, and just not on tagged commits?  I would think this is possible, but maybe it would confuse people.  Or would you rather Circle know nothing about network tests and simply document how to run them in the README and let the contributors run those themselves?

**Comment by mlissner** [comment]
I think I'm leaning towards skipping network tests in CI altogether. They create kind of a lot of problems, and the number of times that we actually use the network code is pretty minimal. Plus: They'll usually fail in production before they fail due to a code change. So yeah: Maybe let's just remove those from circle, and then document them in the readme. 

For the slow scrapers, I guess the thing to do is to fix the HTML file to it's smaller and so it parses quickly enough. The slowness exception is there to highlight slow tests so we don't have to wait for them every time. Usually the fix is just to truncate a really long HTML table in the test suite.

**Comment by arderyp** [comment]
great.  Then the current circle config will stay.  I will cleanup the circle config files later today and, if I have time, look into the slow scrapers.  Changing the HTML files with also necessitate changing the compare files, but that's easy enough.  My only concern with shortening the html files is missing out on some use case coverage that inspired us to create the test file in the first place (for example, some weird edge case in row N of the table).  But, I don't think we can know for sure at this point, so nothing else to do but shorten them.  Maybe the README should include a best practice of only including exact use-cases/edge-cases in example files, as opposed to simply copying the web source wholesale.  Though, this is only really a problem for _gigantic_ HTML pages and, even then, usually only when the scraper itself is rather convoluted.

I will close this issue with my cleanup commit later tonight.

**Comment by mlissner** [comment]
Yeah, that summarizes my feelings about truncating these too.

Thanks for the work on this one. It's a nice big change.

**Comment by mlissner** [comment]
And long overdue!
