### ISSUE TITLE
Can it be installed on Windows?

### ISSUE THREAD

**Issue by Sandy4321** [freelawproject/juriscraper#269]
Can it be installed on Windows?

**Comment by mlissner** [comment]
Probably not. I don't think anybody has tried. If you wanted to make it work there, that'd be fine.

**Comment by arderyp** [comment]
Really?  I would think it would work fine on Windows so long as Python and the other dependencies are in place.  haven't tested myself though.

**Comment by mlissner** [comment]
I would have thought that about macOS too, but it somehow turned out not to be true. *Something* won't work, I suspect.
