### ISSUE TITLE
Scrapers broken in production but working in test

### ISSUE THREAD

**Issue by janderse** [freelawproject/juriscraper#270]
There are a few scrapers that are working in development but are broken in production.

Specifically these scrapers: 
wyo
arkctapp
oklaag
ark
or

When these scrapers are run locally they produce new results.  However, the CourtListener Scraper Status Email shows that in production, the scrapers have not produced new results in many months.

This suggests that something is different in production vs development.  Maybe network access is being blocked in production.  Maybe the production scraper manager has more stringent data validation than the sample caller.  It is strange to me that the sample caller is different from the production.  Why not refactor this to run the same code in both development and production?

I tested the scrapers locally using these commands:
```
python juriscraper/sample_caller.py -c opinions.united_states.state.wyo -vv
python juriscraper/sample_caller.py -c opinions.united_states.state.arkctapp -vv
python juriscraper/sample_caller.py -c opinions.united_states.state.oklaag-vv
python juriscraper/sample_caller.py -c opinions.united_states.state.ark -vv
python juriscraper/sample_caller.py -c opinions.united_states.state.or -vv
```

**Comment by arderyp** [comment]
thanks @janderse for digging these up.

I've created separate issues for WYO (#271) and OR (#272).  We've had issues open for ark/arkctapp (#259) and oklaag (#260) for some time, since they've been failing ungracefully in prod for a long time.
