### ISSUE TITLE
 Blocked scraper: opinions.united_states.state.or

### ISSUE THREAD

**Issue by arderyp** [freelawproject/juriscraper#272]
(from #270)

When this scraper is run locally it produces new results. However, the CourtListener Scraper Status Email shows that in production, it hasn't produced new results in many months.

This suggests that something is different in production vs development. Maybe network access is being blocked in production. Maybe the production scraper manager has more stringent data validation than the sample caller. It is strange to me that the sample caller is different from the production. Why not refactor this to run the same code in both development and production?

python juriscraper/sample_caller.py -c opinions.united_states.state.wyo -vv

---

I never use `sample_caller`, but instead use my own local script for testing scrapers against their live sites and example files.  I can corroborate that this scraper is currently parsing 64 opinions, including recently published stuff (see [or.json.zip](https://github.com/freelawproject/juriscraper/files/3505913/or.json.zip))

**This scraper is not throwing errors in prod, but failing silently.**

@mlissner, can you please run the scraper on prod and see if it is parsing results?  If not, we'll have to add this to to list of courts you need to contact.

**Comment by flooie** [comment]
<img width="693" alt="Screenshot 2023-11-21 at 12 01 31 PM" src="https://github.com/freelawproject/juriscraper/assets/6464529/df9c39af-5a66-45e2-8643-da999b6c95fe">
