### ISSUE TITLE
Upgrade selenium

### ISSUE THREAD

**Issue by divergentdave** [freelawproject/juriscraper#280]
The requirements.txt file currently specifies `selenium==2.53.6`, which is three years old. Moreover, this repository is installed last in https://hub.docker.com/r/freelawproject/courtlistener-django, so this version is what that container image ultimately ends up using.

**Comment by mlissner** [comment]
Am I to understand that fixing this is key to fixing the CL bugs because of some install-order thing?

**Comment by divergentdave** [comment]
I haven't identified any issues caused by this old version (other than Firefox/GeckoDriver compatibility) but it is being used in that image due to the order in which projects are installed, and because packages are being installed system-wide.
