### ISSUE TITLE
Move tax court text parsing code to Juriscraper

### ISSUE THREAD

**Issue by mlissner** [freelawproject/juriscraper#283]
In the U.S. Tax court, it's impossible to get the docket number or the citation without parsing the PDF. That's annoying, but the good news is that @flooie just invested the time to figure out how to do both reliably. Right now the fruit of that labor lives in CourtListener, but technically, if we separate our code properly, it should live here. 

This bug is about moving it here. 

The reason we didn't do so at the outset is because it makes the design a bit trickier and we wanted to get it working as fast as possible. The design isn't that bad though. The general idea is that every court scraper gets a new function that takes the text of the document as input and returns a dictionary as output. The returned dictionary has the same keys as the rest of the juriscraper codebase, so you can do something like:

```
scraper = ca2_scraper()
data = scraper.scrape()
pdf = get_pdf(data['link'])
text = get_text(pdf)
data.update(scraper.get_extra_data(text))
```

That way, you could update the data you were able to scrape by pulling additional data out of the PDF.

To pull this off is pretty straightforward at this point:

1. Add a function to the OpinionSite class that just returns an empty dict. That'll make sure that every scraper has that function available.

2. In tax.py override that function with the specific fields we're looking for. 

3. Then, in CourtListener (not part of this bug), add a cron job to run the above code and save the new data to the DB.

**Comment by flooie** [comment]
Completed

**Comment by flooie** [comment]
We need to add docket number parsing.

**Comment by flooie** [comment]
This has been finalized and added to master.
