### ISSUE TITLE
Return meta-data to caller as plain Python objects

### ISSUE THREAD

**Issue by janderse** [freelawproject/juriscraper#29]
The current way of returning opinions from scrapers complicates the callers.  While the meta-data may be scraped column-by-column, it generally isn't used that way.  

Possible simplification:

``` python
    # Returns all the scraped cases.  Call after parse().
    # Returns a list of dictionaries, one for each case.
    def get_cases(self)
```

This could also be used to implement to_csv(), to_html(), to_xml(), to_json() generically.

Returns data like:

```
[OrderedDict([
    ('case_dates', '2014-06-30'), 
    ('case_names', u'93-06 994'), 
    ('download_urls', 'http://www.va.gov/vetapp14/Files4/1429545.txt'), 
    ('precedential_statuses', u'Unpublished'), 
    ('docket_numbers', u'93-06 994'), 
    ('neutral_citations', u'1429545')]),
 OrderedDict([
    ('case_dates', '2014-06-30'), 
    ('case_names', u'13-34 313'), 
        ...
    ('neutral_citations', u'1429590')]),
]
```

For existing scrapers this would suffice:

``` python
    def get_cases(self):
        cases = []
        for attr in self._all_attrs:
            values = getattr(self, attr)
            if (values is None):
                continue
            i = 0
            for value in values:
                if (len(cases) <= i):
                    cases.append(collections.OrderedDict())
                if (isinstance(value, datetime.date)):
                    value = value.isoformat()
                cases[i][attr] = value
                i += 1
        return cases
```

**Comment by voutilad** [comment]
Not sure if this is still open, but in Python 3.6 this is a natural property (orderedness?) of `dict`s if I'm correct: https://mail.python.org/pipermail/python-dev/2016-September/146327.html

**Comment by mlissner** [comment]
We can close this actually. You can get plain dicts back and iterate on them in the current version. The ordering of the keys in the dicts is still random, but I'm not sure how that matters. I can't imagine a caller caring if the `case_name` key comes before or after the `date_filed` key or whatnot. 

Closing!
