### ISSUE TITLE
Broken scraper: opinions.united_states.state.texag

### ISSUE THREAD

**Issue by audiodude** [freelawproject/juriscraper#290]
The initial page that this scraper requests (https://www.texasattorneygeneral.gov/opinion/index-to-opinions) now redirects to:

https://www.texasattorneygeneral.gov/attorney-general-opinions

Which doesn't have any useful information. There is now this "index to opinions" page: https://www.texasattorneygeneral.gov/opinions but it looks like it's not quite in the format the scraper expects.

**Comment by arderyp** [comment]
see #262
