### ISSUE TITLE
Broken scraper: opinions.united_states.state.kan(ctapp)

### ISSUE THREAD

**Issue by audiodude** [freelawproject/juriscraper#296]
Looks like the site got shuffled around and the page that we previously scraped isn't there anymore:

```
HTTPError: 404 Client Error: Not Found for url: https://www.kscourts.org/Cases-and-Opinions/Date-of-Release-List/
```

**Comment by arderyp** [comment]
I'm working on this now

**Comment by arderyp** [comment]
published: https://www.kscourts.org/Cases-Opinions/Opinions/Published

unpublished: https://www.kscourts.org/Cases-Opinions/Opinions/Unpublished

while we are at it, we should add oralarg scraper:https://www.kscourts.org/About-the-Courts/Supreme-Court/Oral-Arguments/Oral-Argument-Archives

**Comment by arderyp** [comment]
I've got a fix for this @mlissner but I need your input first, see [this](https://github.com/freelawproject/juriscraper/issues/303#issuecomment-593156837)

**Comment by arderyp** [comment]
fixed in commit: https://github.com/freelawproject/juriscraper/commit/f1b32a6959ef78eaa59dc3e2f8a1a09ba5f8813c
