### ISSUE TITLE
Ditch PhantomJS 

### ISSUE THREAD

**Issue by mlissner** [freelawproject/juriscraper#305]
The latest version came out in 2016 and it's a dead end. What are good replacements looking like these days?

**Comment by audiodude** [comment]
Chrome has a version called 'headless Chrome', which launches in the background and runs without any windows open. I've successfully used it for integration testing, not sure if it's capable of hitting live websites.

**Comment by jraller** [comment]
I've had some luck with https://developers.google.com/web/tools/puppeteer though it did have some issues with browser extensions in the version I was trying to use.

**Comment by arderyp** [comment]
I like the headless chrome option because, once its configured on the server, swapping it in for PhantonJS should be really easy

**Comment by audiodude** [comment]
I was able to drop in Headless Chrome via [Chromedriver](https://chromedriver.chromium.org/) and get at least one scraper to work with no other changes.

Some things to note:
1. Google Chrome will have to be installed, of course, and we will have to keep a variable that keeps track of its executable path. This is hairier than phantomjs, which just lives at /usr/local/bin. This is the actual path of wherever Chrome is on your Windows/Mac/Linux system.
2. The `chromedriver` executable will have to be installed as well, and here's the hairy part, *its version much match the Chrome version*.
3. The `chromedriver` executable will have to be in the PATH when the scraper process runs.
4. All of the scrapers that initialize webdriver manually in their `download` methods will have to be uploaded. I think @arderyp you were moving towards something like this with `OpinionSiteWebDriven`?

**Comment by arderyp** [comment]
@audiodude, yes, my last commit was a first step.  I will update all Selenium scrapers to extend the either `OpinionSiteWebDriven` or `OpinionSiteLinearWebDriven`, both of which pull from a unified `WebDriven` class, then the webdriver instantiation/configuration will be consolidated in 1 place..

**Comment by mlissner** [comment]
Is it crazy to think this might be the best solution? https://github.com/SeleniumHQ/docker-selenium/

I think you just run it as a docker image, and then you connect to it via ports. So once it's running, you can do things like (from CL tests):

```
    def _create_browser():
        options = webdriver.ChromeOptions()
        if settings.SELENIUM_HEADLESS is True:
            options.add_argument("headless")
        options.add_argument("silent")
        options.add_experimental_option("w3c", False)

        # Workaround for
        # https://bugs.chromium.org/p/chromium/issues/detail?id=1033941
        options.add_argument(
            "--disable-features=AvoidFlashBetweenNavigation,PaintHolding"
        )

        if settings.DOCKER_SELENIUM_HOST:
            capabilities = options.to_capabilities()
            return webdriver.Remote(
                settings.DOCKER_SELENIUM_HOST,
                desired_capabilities=capabilities,
            )
        return webdriver.Chrome(chrome_options=options)
```

That should give us a functional version of Chrome on the server? I shudder to wonder what it'd take to install Chrome otherwise. Can you install only a headless Chrome, for example, on a server?

**Comment by arderyp** [comment]
You can definitely install chrome on linux.  How easy it is to install and configure might depend on your distribution.  That doesn't concern me as much as the version parity that @audiodude mentioned, which would mean that the Chrome instance on all of our dev machines (I use my personal laptop) must all be in sync with each other and juriscraper production.  If I'm not misunderstanding @audiodude, I'm not sure how realistic this would be.  Your docker approach seems fine, though the thought of installing/running docker on development instances isn't great, IMO.

**Comment by audiodude** [comment]
I think the docker image makes a lot of sense, and likely solves the version synchronization issue.

There should be some notion of environment, where you declare a WebDriver implementation that you would like to use (docker, local install, etc) and the proper implementation is selected based on your config.

**Comment by arderyp** [comment]
> Including, WEBDRIVER = None if you don't want to run any webdriver scrapers for some reason.

I like this idea.

**Comment by mlissner** [comment]
> You can definitely install chrome on linux.

Yes, but like, on a server? I wonder how many GUI libraries it'd bring along for the ride. 

> the thought of installing/running docker on development instances isn't great

We do this for CourtListener now (for running tests), and it works really nicely. But you do have to install Docker as the first hurdle. 

We could make docker optional, so that if you passed the right env vars, it'd choose a remote Chrome Driver and if not it'd do a local one. I do worry though that people will wind up with bugs that way that don't happen in prod because their local install is funky. 

I wonder if building Juriscraper into a dockerized service is a terrible idea. That'd *require* the docker dependency, but it'd allow all of its versions and installation to be entirely simplified. Hm.

**Comment by arderyp** [comment]
Well, I'll install docker if it becomes a dependency lol

**Comment by mlissner** [comment]
Yeah, it does feel a little strange though to have it as a dependency, right? Like the right way to do this is to make Juriscraper a dependency for docker, not the other way around.

**Comment by audiodude** [comment]
It's not just the "dependency" on Docker, with regards to having to install Docker. It's also the fact that you have to make sure your selenium-docker image is up and running and mapped correctly before you can scrape any webdriver scrapers.

**Comment by arderyp** [comment]
> It's not just the "dependency" on Docker, with regards to having to install Docker. It's also the fact that you have to make sure your selenium-docker image is up and running and mapped correctly before you can scrape any webdriver scrapers.

this actually concerns me deeply... if this is necessary, I could foresee myself cursing my machine

**Comment by mlissner** [comment]
Well, it wouldn't be that bad. If you didn't have selenium up and running in docker, it'd just crash until you did. On CourtListener once I got it set up for everybody, it's been pretty smooth.

**Comment by arderyp** [comment]
I've consolidated all Selenium scrapers to extend from `WebDriven` (via `OpinionSiteWebDriven` or `OpinionSiteLinearWebDriven`).  So, if we switch to chrome, we should be able to drop the replacement in `WebDriven` and that should be it.

**Comment by mlissner** [comment]
See also: #280, which calls for Upgrading Selenium. Perhaps we can close that out too if we ditch it entirely.

**Comment by arderyp** [comment]
error I just recieved from running selenium scraper:

```
/home/me/.virtualenvs/juriscraper/local/lib/python2.7/site-packages/selenium/webdriver/phantomjs/webdriver.py:49: UserWarning: Selenium support for PhantomJS has been deprecated, please use headless versions of Chrome or Firefox instead
  warnings.warn('Selenium support for PhantomJS has been deprecated, please use headless '
```

**Comment by mlissner** [comment]
I'm unclear, @arderyp is this a big deal? Like, are our scrapers broken or does this just mean they will be, or.... ?

**Comment by arderyp** [comment]
I believe its just a warning, like the pip warnings about Python2.  These systems are just reminding us that we are using outdated technology that's no longer supported.

**Comment by mlissner** [comment]
So, I forgot this issue existed, needed phantomjs to be remote accessible today, and went ahead and did it. Thanks to @arderyp's ground work, and experience we have running tests with selenium over in CourtListener, it was super easy. 

I'm also happy to say that I did exactly everything that we discussed here without even referring remembering this conversation existed. I guess it made an impact. 

So. Y'all can go check out the readme, it has the details, but basically:

 - Current functionality is mostly maintained. If you want to use phantomJS and have it installed, great, that remains the default. 
 - We had some old code that threw a `warning` and then supported a weird location for phantomJS. I removed that (see readme).
 - There are new environment variables that you can use to tell Juriscraper to connect to a remote webdriver. 

Overall, I think this is great. There's not a whole lot more need for phantomJS, but there's no need to remove it for now at least. I imagine once we all get used to doing dev while using a remote webdriver, we'll remove it eventually, but no rush really. 

Aside from breaking our dependency on phantomJS, this also means that by using a VNC viewer (I use Remmina), we can actually *see* what the webdrivers see, including while using our debuggers. All in all, this only took me a few hours.

Marking dooooone!

**Comment by mlissner** [comment]
(I think this is the first time there's been a productive conversation I forgot existed, that I later discovered, and where I didn't have to go back and fold in some of the good suggestions from the conversation. Whew!)
