### ISSUE TITLE
PACER reports.py PDF download query should be POST, not GET

### ISSUE THREAD

**Issue by mseflek** [freelawproject/juriscraper#310]
I think the `_query_pdf_download` function in `pacer/reports.py` needs to use a POST method, not a GET method.

You can verify this for [this](https://ecf.nceb.uscourts.gov/doc1/13008735280) 1 page doc for bankruptcy and [this doc](https://ecf.cand.uscourts.gov/doc1/03503892159) for district courts. Trying to download these files by clicking on View Document shows a POST request being made in Chrome's developer tools.

I could certainly be wrong or missing something, but with the GET request on python 2.7 the function doesn't return anything for 5+ minutes until I stop the kernel. With a POST request the rest of the code, including the `download_pdf` function, runs fine and returns the correct PDF.

**Comment by mlissner** [comment]
Hm, could be something new, but in general you can do a GET or POST to get these. We've used the function to get thousands of PDFs.

What do you mean by stopping the kernel?

**Comment by mseflek** [comment]
Well this is embarrassing. I tried to come up with a reproducible example and everything was working fine, so it must have been something odd in my original scraping code. Despite several hours troubleshooting it for a mistake I made I must've missed something. My apologies for the unnecessary headache.

**Comment by mlissner** [comment]
No worries! Let us know if you have further questions or drop us a line if you want to join our Slack group.
