### ISSUE TITLE
Need scraper for D.C. Circuit orders of public interest

### ISSUE THREAD

**Issue by brianwc** [freelawproject/juriscraper#321]
[https://www.cadc.uscourts.gov/internet/orders.nsf](https://www.cadc.uscourts.gov/internet/orders.nsf)

While there is a scraper for the "opinions" of the D.C. Circuit, we apparently do not collect the "Orders of Public Interest" where they put the occasional "order" for higher-profile or newsworthy cases. That's a mistake because they are "of Public Interest" and the D.C. Circuit is a particularly important appellate court due to the number of government-related cases it hears.

**Comment by mlissner** [comment]
Expect these soon, @brianwc. Thanks for filing the request (a year and a half ago).
