### ISSUE TITLE
Backscrape all the CA cases we lack

### ISSUE THREAD

**Issue by mlissner** [freelawproject/juriscraper#324]
This came up in the context of the CA unpublished cases, but we don't necessarily have to stop there. I believe @ikeboy is going to take a run at this.

**Comment by ikeboy** [comment]
I could use an export of case numbers and precedential status from calctapp for the backscraping. From https://www.courtlistener.com/?stat_Non-Precedential=on&order_by=dateFiled+desc&court=calctapp&type=o&page=2, CL currently has 91,367 precedential cases and 26,335 non-precedential cases. 

That would help reverse engineering the case number formula.

**Comment by flooie** [comment]
I wonder if this is complete?

**Comment by mlissner** [comment]
Seems like it's not, but you'll be reviewing gaps and filling them over the next six months anyway, so no point in keeping this really old issue around. We can open a new, fresh one when the time comes.
