### ISSUE TITLE
Fix ky scraper and add kyctapp scraper

### ISSUE THREAD

**Issue by ikeboy** [freelawproject/juriscraper#327]
The PDFs for kyctapp are at https://kycourts.gov/courts/coa/pages/minutes.aspx, PDFs for ky are at https://kycourts.gov/courts/supreme/Pages/SupremeCourtMinutes.aspx, and case names can be gotten by searching the case number in https://appellatepublic.kycourts.net/search/case. Note that you need to remove the 00 after the second dash in the number, as well as remove the trailing letters, for that search to work - e.g. 2019-CA-000208-MR turns into 2019-CA-0208. 

Also, I saw https://github.com/freelawproject/juriscraper/issues/261, can you check if the new URL (apparently added around April) also blocks production?

**Comment by ikeboy** [comment]
Actually, the minutes PDFs have the case names in them. But to get them you have to parse the PDF and it's combined with other information like judge name - see e.g. http://apps.courts.ky.gov/Supreme/Minutes/MNT072020.pdf

**Comment by mlissner** [comment]
The first two links seem to work, but the third stalls. Seems like this is a dup of #261? I guess I need to call again?

**Comment by ikeboy** [comment]
Do you think the case names from the minute PDFs are good enough?

**Comment by arderyp** [comment]
scraping PDFs is something we've avoided so far

**Comment by ikeboy** [comment]
Can you try this:

`curl 'https://appellatepublic.kycourts.net/api/api/v1/cases/search?queryString=true&searchFields%5B0%5D.searchType=Starts%20With&searchFields%5B0%5D.operation=%3D&searchFields%5B0%5D.values%5B0%5D=2019-CA-0208&searchFields%5B0%5D.indexFieldName=caseNumber' `

**Comment by arderyp** [comment]
```
$ curl 'https://appellatepublic.kycourts.net/api/api/v1/cases/search?queryString=true&searchFields%5B0%5D.searchType=Starts%20With&searchFields%5B0%5D.operation=%3D&searchFields%5B0%5D.values%5B0%5D=2019-CA-0208&searchFields%5B0%5D.indexFieldName=caseNumber'
{"resultItems":[{"id":"7eee6f2062fc6e6865364a6c52ff300e97e9f126a249c97b81d9ef799237118a","indexID":"150000","rowMap":{"caseNumber":"2019-CA-0208","caseID":"7eee6f2062fc6e6865364a6c52ff300e97e9f126a249c97b81d9ef799237118a","closed":false,"shortTitle":"WILLOW GRANDE, LLC VS CHEROKEE TRIANGLE ASSOCIATION, INC., ET AL","caseType":"CIVIL"},"score":5.0}],"headers":[{"label":"Case Title","type":"String","property":"shortTitle","sortProperty":"shortTitle.sort","useHighlighting":false},{"label":"Case Type","type":"String","property":"caseType","sortProperty":"caseType.raw","useHighlighting":false},{"label":"Final","type":"Boolean","property":"closed","sortProperty":"closed","useHighlighting":false}],"facets":[{"searchFacetName":"Court","searchFacetField":"court","searchFacetOrderBy":1,"searchFacetType":"String","searchFacetItems":[{"display":"Kentucky Court of Appeals","value":"Kentucky Court of Appeals","count":1,"selected":false}]},{"searchFacetName":"Case Final","searchFacetField":"closed","searchFacetOrderBy":6,"searchFacetType":"Boolean","searchFacetItems":[{"display":"false","value":"false","count":1,"selected":false}]}]}
```

**Comment by arderyp** [comment]
@mlissner will have to test from PROD server

**Comment by arderyp** [comment]
@ikeboy do you know of a similar API for non-appellate-KY  cases, to use for the regular ky scraper?

**Comment by ikeboy** [comment]
Also, what's the general philosophy on blocked scrapers and using work-arounds? E.g. this site works fine over privateinternetaccess VPN for me, if it is blocked on production could you just set up a VPN?

**Comment by ikeboy** [comment]
This site should get both court of appeals and supreme court for ky.

**Comment by mlissner** [comment]
OK, so that link above doesn't work on prod, no, and I agree with @arderyp that parsing PDFs is kind of too horrible to do. 

Our general policy on proxies is that we don't do them and we instead rely on talking to the court to get them to do the right thing. 

That said, I recently made an AWS lambda thing that checks if URLs are up or not:

Compare:

https://3xuza7beb3.execute-api.us-west-2.amazonaws.com/v1/get?url=https://www.google.com&timeout=5

To:

https://3xuza7beb3.execute-api.us-west-2.amazonaws.com/v1/get?url=https://www.goooooogle.com&timeout=5

It's very MVP, so it only returns whether the `url` works, but it could be extended to be a proxy for us. I don't know about using VPNs or how hard that'd be, but at this point I'm not opposed if it's easy?

**Comment by arderyp** [comment]
it would be cool to have a proxy requester, for when we are being blocked, but unless we had a swarm, it would just lead to the proxy getting blocked eventually. Ultimately, I think it should be considered a last ditch effort--getting the courts to permit access is definitely the ideal solution.  Is there some legal avenue to consider here?  Should these court sites serving public data be _allowed_ to block projects like ours, assuming we are pinging them at a "reasonable" rate?

**Comment by mlissner** [comment]
I think b/c it's a lambda, it does wind up coming from different IPs each time, but I agree philosophically. I'm sending an email to their PIO now.

**Comment by ikeboy** [comment]
I mean, for something like KY where you'd be pinging them a handful of times a day at most, I don't think it would be unmanageable. I'm curious how hard you were hitting them the first time when it was blocked. 

For what it's worth, I've built and ran scrapers that hit commercial sites thousands of times a day or more, it's not that complicated and getting access to a proxy pool to support that is extremely cheap. At the scale we're talking about here, it wouldn't cost more than a couple bucks a month. 

I've used luminati in the past, their datacenter IPs are cheap and they've got a user friendly API.

**Comment by mlissner** [comment]
Let's give them a few days to respond to my message. If we don't hear back, I'm in favor of using a proxy. Seems like the most logical thing to do.

**Comment by mlissner** [comment]
PIO replies that she's sent it to IT.

**Comment by arderyp** [comment]
woah, good to know @ikeboy regarding the proxy pools, I didn't know about that.  Also good to know @mlissner about the lambda capability you referenced.  I didn't know about that either.  Clearly I'm behind the times!

So would an easy cheap solution be to simply run jusicraper wholesale from an AWS lambda instance.  Please excuse my ignorance if this is a nonsensical questions. 

@ikeboy, to answer your question, I believe we generally scrape any given court site once a day.  If its a janky site that doesn't display all the parsable data on one page, and we have to process multiple sub-pages to fetch all the data we need, this can turn into multiple pings.  But even in those cases, its probably low hundreds at the absolute most.  Please correct any of this thats wrong @mlissner.

I think KY and other courts simply see our "juriscraper" User Agent string and get sketched out.

**Comment by mlissner** [comment]
We crawl hourly, @arderyp, but yeah, the point remains that it's practically nothing.

I'm not opposed to using lambda more for this, but I don't have the time for it, and it would introduce complexity I wouldn't want to deal with. Proxies might be the easier thing, but I really don't know how those APIs work.

**Comment by ikeboy** [comment]
It's trivial to add a proxy to a `requests` call. Looks like you could just add a `PROXY_URL` and `PROXY_PASSWORD` to the settings file, and add a couple of lines to the `AbstractSite` class to use those settings if requested, then enable it only for the scrapers that need it.

**Comment by ikeboy** [comment]
https://kcoj.kycourts.net/Content/docs/TermsOfUse2-4-13.pdf

>The Kentucky Court of Justice does not allow any spiders, data mining, or data scraping of this Site. Use of software intended to discover and extract data from this Site through automated, repetitive querying for the purpose of collecting such data is absolutely prohibited. Absolutely no batch processes are allowed to run against this Site or the data contained herein. A limited exception is provided to general purpose internet search engines and noncommercial public archives that use tools to gather information for the sole purpose of displaying hyperlinks to this Site, provided they do so from a stable IP address or range of IP addresses using an easily identifiable agents and comply with our robots.txt file. The AOC reserves the right to restrict the number of sessions from a specific IP address, restrict access from a specific IP address to the web site if the IP is engaging in such activities, or take further action as needed.

I assume we fall into that exception?

**Comment by arderyp** [comment]
Sounds like it, nice find!

**Comment by mlissner** [comment]
Hopefully so, yeah. I've got an email with their IT on it, but still no word on a fix.

**Comment by mlissner** [comment]
OK, I'm told:

> Your IP address was generating some type malicious activity at some point which was the reason for the block.  I've removed the block and you should be able to access the resource.

Checking curl seems to indicate it's fixed as well.

More to do here?

**Comment by ikeboy** [comment]
Well, the scraper needs to be rewritten to use the new URLs, and maybe we should scale it up slowly to make sure it doesn't trigger anything again. Then we also need backscrapes, which would also be prudent to spread out.

**Comment by mlissner** [comment]
I'm OK with triggering their thing again. My goal is to get whitelisted. I'd say we do what we want, and if we trigger it, we fight that fight.

**Comment by arderyp** [comment]
Yeah, whitelist seems like the real solution.

**Comment by ikeboy** [comment]
https://github.com/freelawproject/juriscraper/pull/329 rewrote the scraper. I didn't change the comments, but those should probably be updated to document the changes.

**Comment by flooie** [comment]
closing this - as it seems like we've been able to scrape this for the last few years
