### ISSUE TITLE
CA4 and HTTP request problem

### ISSUE THREAD

**Issue by Altabeh** [freelawproject/juriscraper#332]
I am having a problem downloading ca4 cases. The root cause of this problem at least as far as I can tell is that the court form data are sent over HTTPS protocol whereas, in ca4.py, the initialization of the base URL is done over HTTP. So I think `self.url ` has to be `https://www.ca4.uscourts.gov/DataOpinions.aspx`. At least this fixed the problem for me.

**Comment by mlissner** [comment]
Weirdly, this was actually fixed yesterday. We'll deploy it soon. Closing, but feel free to continue commenting/responding/etc.
