### ISSUE TITLE
Unpegged "feedparser" Dependency

### ISSUE THREAD

**Issue by cgdeboer-toptal** [freelawproject/juriscraper#334]
4 days ago, `feedparser` (a dependency of this project) [dropped all support](https://github.com/kurtmckee/feedparser/releases/tag/6.0.0) for Python2. 
***
We should probably peg the `juriscraper` requirement to release https://github.com/kurtmckee/feedparser/releases/tag/5.2.1 .

The long term answer is move the whole code-base to python3, and that has been discussed ad nauseam in other issues, but should be prioritizes (happy to help !).

**Comment by mlissner** [comment]
Thanks for filing this. Yeah, we'll need to peg feedparser for the time being. 

Do you have experience doing Python 3 upgrades? We'd kill for the help.

**Comment by cgdeboer-toptal** [comment]
I have done some Py3 upgrades, mostly of the “Leave Python 2 behind” variety. Seems like that effort would require a three-ifying of CL as well (if I read the comments in other issues correctly).


Is there an EOL in sight for Python 2 support within the Freelaw Ecosystem ? Or does this project need to support py2 and py3 for a while. I’m sure all are aware that we are already in the post-support  era of Python 2, the sun has set (https://www.python.org/doc/sunset-python-2/).
***
I’ll push a PR to peg the dependency mentioned in the the subject. What’s the pypi release schedule like for this project ?

**Comment by mlissner** [comment]
It's probably best from a resource perspective if we just go full Python 3 all at once. That should be easier than trying to make code that works on both. Probably the way to do it is to just upgrade *everything* in the requirements.txt file, and go through and fix anything that's broken. I've attempted to read all the upgrade notes in the past, but it's just impossible at this point.

As far as Juriscraper goes, we could bump to version 2.0.0, and say it only supports Python 3, I think that'd be fine. 

----

For pypi, it auto-releases according to tags on commits to `master`. I'm not sure how that works with PRs, but if you need a new version cut, I can make sure it happens.
