### ISSUE TITLE
Upgrade to Python 3 (Major Version 2.0.0, for repo)

### ISSUE THREAD

**Issue by cgdeboer-toptal** [freelawproject/juriscraper#336]
A few requests have come in (including my own) for upgrading this great tool to Python 3. Some of the dependencies of the project have dropped support for Python 2 altogether (`feedparser` for example). Previous efforts have been made to move the code-base to python3, it's time to try and finish that off.

###### Work Plan
- update code base
- ensure tests are passing
- integration testing (in other dependent repos)
- update the docs / readme.
- cut a new `2.0.0-rc` version.
- perhaps some tweaking after that.
- cut a new `2.0.0` version.

***

@mlissner does this seem like an appropriate linear work plan for this ?

**Comment by mlissner** [comment]
Yep, sounds right to me. What do you think about the problem that if Juriscraper is py3 and the rest is py2, they'll be incompatible? I don't know when CL will be upgraded, so it feels like a mistake to release JS 2.0.0 on py3 and have them incompatible for any period of time.

**Comment by cgdeboer-toptal** [comment]
There's a couple options, depending primarily on the amount of time "the rest" needs to support Python 2. Here are two that stand out as things that might match the objectives of this project.

1. fork the project(longest lived python 2, most annoying maintenance track IMHO, keeping both up to date)
    - old python2 dependent projects point at the existing repo, new ones at the py3 one.
2. release `2.0.0`  fully drops Python 2 support. All future development effort continues there:
    - old python2 dependent projects version lock the dependency to the latest **1.X.X** version.
    - If it was absolutely necessary, critical scraper updates and important security patches could still be made based on the python2 release tag, and a new **1.X.X** version could be cut from that tag.

***

Supporting Python2 for any length of time is probably not prudent at this time. I see Django is a dependency of CL. Their 1.11 version is the last to support Python2, and it ended extended support earlier this year.

#### Figure 1
![image](https://user-images.githubusercontent.com/66377349/93583214-8965eb00-f971-11ea-8dea-4032481f6b6a.png)

***

How many dependent python projects (that freelawproject controls) are out there besides CL ?

**Comment by arderyp** [comment]
I'd say everything needs to be updated.  It just has to happen.  It's not going to be fun, but there is simply no other choice.

**Comment by mlissner** [comment]
> How many dependent python projects (that freelawproject controls) are out there besides CL ?

If we had more resources I'd say we should make this cross-compatible, or maintain a fork or a branch for py2 support, but we're strapped for resources, so I think a clean break is fine. If those using JS want to get features or fixes from the py3 `master` branch, they can fork and support py2 or they can upgrade to py3.

> I'd say everything needs to be updated. It just has to happen. It's not going to be fun, but there is simply no other choice.

I agree, so I think the strategy might be to land everything all at once. Upgrade all CL and JS dependencies once and for all to their latest versions, upgrade our code to work again, and then push all at once. 

(At some point I'll figure out how to get py3 on our server! It might be a good time for us to move to an AWS-hosted server.)

**Comment by flooie** [comment]
@arderyp @mlissner @cgdeboer-toptal 

We have an almost complete PR for this issue.  See https://github.com/freelawproject/juriscraper/pull/343

As stated above this is meant to coincide with CL's move to python 3.8.

**Comment by mlissner** [comment]
DONE!
