### ISSUE TITLE
Question regarding docket entry attachments

### ISSUE THREAD

**Issue by cgdeboer-toptal** [freelawproject/juriscraper#339]
Say I get a scrape result for a case, that has an entry like figure 1:

#### Figure 1
```json
{
    "demand": "",
    "date_terminated": null,
    "docket_entries": [{
        "date_filed": "2020-08-20T00:00:00",
        "document_number": "561",
        "description": "TRANSCRIPT OF PROCEEDINGS before Judge James E. Boasberg held on 8-10-2020; Page Numbers: 1-27. Date of Issuance:8-20-2020. Court Reporter/Transcriber Lisa Griffith, Telephone number 202-354-3247, Transcripts may be ordered by submitting the Transcript Order FormFor the first 90 days after this filing date, the transcript may be viewed at the courthouse at a public terminal or purchased from the court reporter referenced above . After 90 days, the transcript may be accessed via PACER. Other transcript formats, (multi-page, condensed, CD or ASCII) may be purchased from the court reporter.NOTICE RE REDACTION OF TRANSCRIPTS: The parties have twenty-one days to file with the court and the court reporter any request to redact personal identifiers from this transcript. If no such requests are filed, the transcript will be made available to the public via PACER without redaction after 90 days. The policy, which includes the five personal identifiers specifically covered, is located on our website at www.dcd.uscourts.gov. Redaction Request due 9/10/2020. Redacted Transcript Deadline set for 9/20/2020. Release of Transcript Restriction set for 11/18/2020.(Griffith, Lisa) (Entered: 08/20/2020)",
        "pacer_doc_id": "04508005331",
        "pacer_seq_no": "2434"
    }],
    "docket_number": "1:16-cv-01534",
    "date_discharged": null,
    "date_converted": null,
    "jurisdiction": "U.S. Government Defendant",
    "mdl_status": "",
    "case_name": "STANDING ROCK SIOUX TRIBE v. UNITED STATES ARMY CORPS OF ENGINEERS",
    "parties": [],
    "date_filed": "2016-07-27T00:00:00",
    "nature_of_suit": "893 Environmental Matters",
    "jury_demand": "None",
    "assigned_to_str": "James E. Boasberg",
    "court_id": "dcd",
    "cause": "05:0706 Judicial Review of Agency Actions",
    "referred_to_str": ""
}

```
I'm wondering what the best practice is for retrieving the actual document associated with `pacer_doc_id: 04508005331`. I've seen some "download_pdf" methods, but those seemingly are about getting a PDF of the entire docket entry, not the PDF attachment itself (and I could be WAY wrong on that). 

I've done a cursory review of the documentation, and some of the seemingly related code. Any guidance on where I should look in the codebase for that functionality, if it indeed exists ?

/tag question

**Comment by mlissner** [comment]
download_pdf will work for attachments or main documents. They'll have different `pacer_doc_id` values.

**Comment by cgdeboer-toptal** [comment]
Thanks for the tip @mlissner !  I have district court PDF downloads working with the attachments. 

If I might be so bold... related question on accessing related PDF documents from Appeals counts. ... the Appeals [download_pdf](https://github.com/freelawproject/juriscraper/blob/master/juriscraper/pacer/appellate_docket.py#L260) seems to yield  `None` response. 

Say we have a function called "retrieve_documents" that seeks to get PDF content for a particular `pacer_doc_id` listed in an appellate docket entry:

```python
def retrieve_documents(court_id, docket, pacer_doc_id,
                       user=None, pwd=None):
    adr = AppellateDocketReport(court_id=court_id,
                                pacer_session=PacerSession(username=user, password=pwd))
    response = adr.download_pdf(pacer_doc_id)
```

- court_id = "ca3"
- docket = "19-1191" *(un-used at the moment)*
- pacer_doc_id = "003013389677"

The response comes back from juriscraper as `None`... digging further, the response that comes back from the `session.get` request is actually a 200 with some strange content. It seems to suggest my PACER creds are invalid, but I have checked them 5 times over, and used them to login to PACER directly to acquire this same document. 

```bash
ipdb> !r
<Response [200]>
ipdb> !r.text
u'<meta http-equiv="REFRESH" content="0; url=TransportRoom?servlet=InvalidUserLogin.jsp&validLogin=&strJSPName=ShowDoc%26pacer=i%26dls_id=003113389677">\n'
```

Is the way I'm calling for that PDF content the intended design, or is there a more idiomatic incantation ?

**Comment by mlissner** [comment]
This seems right, but we don't do a lot with appellate content unfortunately. It could be that it broke since we last looked at it. It looks like it's probably the login code that's having some sort of issue. If that's the case, before you debug too much further, you should probably look at how PacerSession is set up. It has some funky heuristics that it uses to determine if the login succeeded that are something of a whitelist. Could be the whitelist needs another entry, or that the approach to getting appellate PDFs isn't quite working.

**Comment by cgdeboer-toptal** [comment]
Understood. If anything interesting turns up, I'll turn it into a PR.
