### ISSUE TITLE
Convert Juriscraper tests from CircleCI to Github

### ISSUE THREAD

**Issue by mlissner** [freelawproject/juriscraper#342]
Make sure that we tell everybody in Juriscraper and dev channels.

**Comment by flooie** [comment]
Without removing things from CircleCI - we have moved testing to Github Actions.  Additionally, we've added a new workflow action to push new version to pypi.

**Comment by mlissner** [comment]
Needs readme and final removal of circleci, but Github is working.

**Comment by flooie** [comment]
This is complete.
