### ISSUE TITLE
Idea: Log File Location as Environment Var

### ISSUE THREAD

**Issue by cgdeboer-toptal** [freelawproject/juriscraper#347]
Allow setting a `JURISCRAPER_LOG_FILE` environment variable. Use that, and default to what is already there. https://github.com/freelawproject/juriscraper/blob/7d6d47b4cb5454d769fe819fa6d931273bf2874d/juriscraper/lib/log_tools.py#L7

This allows the package user to define a log file location, and can avoid the warning below.

```
Warning: No such file or directory: /var/log/juriscraper/debug.log. Have you created the directory for the log?
Juriscraper will continue to run, and all logs will be sent to stderr.
```

**Comment by mlissner** [comment]
It'd be nice to be done with that warning message, and I like your proposal. Let's do it.

**Comment by mlissner** [comment]
By the way, @flooie is still researching how to do auto-releases, by the way. We have a github action for it that works when we push, but it doesn't work when PRs are merged, apparently. I'm guessing this one is an annoyance you've already worked around, but let us know if you want a release just for this.
