### ISSUE TITLE
NY App Div CaseNames lack proper spacing

### ISSUE THREAD

**Issue by brianwc** [freelawproject/juriscraper#36]
See cases from Oct. 23 such as MaxonAlcoHoldings,LLCvSTSSteel,Inc. (N.Y. App. Div.  2014)  https://www.courtlistener.com/?q=&stat_Precedential=on&order_by=dateFiled+desc&court=nyappdiv

**Comment by arderyp** [comment]
is this still an issue?  I found the [page](http://decisions.courts.state.ny.us/ad3/calendarpages/nc10232014.htm) with @brianwc's example above, pointed our current nyappdiv_3rd scraper at this specific page, scraped it, dumped the json, and I see what appears to be a properly formatted case name:  

```
{
    "case_names": "Maxon Alco Holdings, LLC v. STS Steel, Inc.",
    "case_dates": "2016-03-03",
    "blocked_statuses": false,
    "download_urls": "http://decisions.courts.state.ny.us/ad3/Decisions/2014/517378.pdf",
    "precedential_statuses": "Published",
    "case_name_shorts": "",
    "docket_numbers": "517378"
},
```

That being said, there is an issue with the parsing of dual docker numbers.  Some entries legitimatly show dual docket numbers with a slash delimeter, like xxxxxx/yyyyyy, but it appears that some entries have a slash delimeter, but no second case number (maybe human error?).  On the same page linked above, we see "515342/Matter of Neroni v Granis", which parses to:

```
{
    "case_names": "of Neroni v. Granis",
    "case_dates": "2016-03-03",
    "blocked_statuses": false,
    "download_urls": "http://decisions.courts.state.ny.us/ad3/Decisions/2014/515342-515341.pdf",
    "precedential_statuses": "Published",
    "case_name_shorts": "Granis",
    "docket_numbers": "515342/Matter"
},
```

I can fix this later in the week.

**Comment by mlissner** [comment]
Yeah, let's close this one since it's fixed, and I'll leave the docket issue in your hands? Or we can open another issue for that, if you wish. Be great to get that fixed.

**Comment by arderyp** [comment]
@mlissner yup, I'll submit a PR to fix the docket number issue shortly
