### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by dmvj** [freelawproject/juriscraper#391]
In the readme, the link to sample_caller.py is broken.

Is: https://github.com/freelawproject/juriscraper/blob/master/juriscraper/sample_caller.py

Should be: https://github.com/freelawproject/juriscraper/blob/main/sample_caller.py

**Comment by mlissner** [comment]
Thanks Dan. Want to do a PR?

**Comment by dmvj** [comment]
> Thanks Dan. 

No problem, Mark. (I'm Doug. ;))

**Comment by mlissner** [comment]
Oops, I'm sorry. Totally converted Doug to Dan in my head between reading your email and seeing your screen name. Sorry!
