### ISSUE TITLE
CA9's oral argument scraper is down

### ISSUE THREAD

**Issue by mlissner** [freelawproject/juriscraper#395]
Looks like it has a variety of problems.

**Comment by arderyp** [comment]
@mlissner, it looks like the black lint failed in the build.  I'm woefully out of date on the state of Black linting with this project.  My linter ran and even made some corrections.  Were linting standards changed?  If so, how should I go about implementing the latest lint rules on my dev environment?

**Comment by arderyp** [comment]
I just read the README and ran `pre-commit install`.  This set up a new `pre-commit` file, that seems to have done it.  Sorry about the hiccup.

**Comment by mlissner** [comment]
Oh, excellent.

**Comment by mlissner** [comment]
@satsuki-chan, it looks like you got a helping hand from a volunteer that often works on the scrapers. Lucky you. Phil has been helping with these for years.

Want to look at his changes and reply with your thoughts?
