### ISSUE TITLE
NY App Divs provide neutral citations but we save them as docket numbers

### ISSUE THREAD

**Issue by mlissner** [freelawproject/juriscraper#42]
This is a fairly easy one, but if you look at [the page here][1] you'll see that NY App Div is using neutral citations. Our scraper is recognizing these as docket numbers instead and needs to be updated.

At the same time we need to write a cleanup script to fix the content in CourtListener.

[1]: http://www.courts.state.ny.us/reporter/slipidx/aidxtable_1.shtml

**Comment by arderyp** [comment]
Is this still an issue?  Looks to be pulling dockets now: 

http://www.courts.state.ny.us/reporter/slipidx/aidxtable_1.shtml
https://www.courtlistener.com/opinion/4281988/nexbank-ssb-v-soffer/?q=NexBank%2C+SSB+v+Soffer

**Comment by arderyp** [comment]
If I push a fix, can I close this ticket with the commit, or do you still want to retroactively fix old records?

**Comment by mlissner** [comment]
Not sure I have time to retroactively fix at the moment. I say we close it
once we're getting these properly.
