### ISSUE TITLE
Add support for Python 3.9 and 3.10

### ISSUE THREAD

**Issue by mlissner** [freelawproject/juriscraper#422]
Attempting to run our tests on Python 3.9 and 3.10 failed:

https://github.com/freelawproject/juriscraper/runs/4246065412?check_suite_focus=true

That failed due to the commit here:

https://github.com/freelawproject/juriscraper/commit/476e5b5c35df722d6a1b7452af71e86ad678f154

At a glance, it looks like `feedparser` doesn't work in Python 3.9, and we probably need to upgrade it to fix that issue. I have a vague memory that we haven't upgraded feedparser because they made a bunch of minor (but important) backwards incompatible changes, so it might take a bit of work to get it upgraded.

**Comment by flooie** [comment]
just an fwiw - I just used the current feed parser to update the CAFC RSS feed code.

**Comment by satsuki-chan** [comment]
`feedparser` version **6.0.8** works with Python 3.9 and 3.10.
All tests in the new Python versions passed without problem.

![Screenshot from 2021-12-02 09-16-48](https://user-images.githubusercontent.com/8507838/144450163-6d797cf6-f172-45ca-89f4-7348be52d2a6.png)
