### ISSUE TITLE
Need to Standardize Testing URLs

### ISSUE THREAD

**Issue by flooie** [freelawproject/juriscraper#450]
Tests are inconsistent in how they generate and download_urls to compare.

This occurs because the scraper normalizes the HREFs during the scraping process with a method that looks like this 

`self.html.rewrite_links(fix_links_in_lxml_tree, base_href==self.request["url"])`

This method iterates over the elements and turns hrefs into absolute urls.  
This doesn't occur and can't necessarily be done in the same way for testing environment. For one, we don't necessarily have the final `request.url` to build the absolute_url.  Secondly, I tried doing a quick regeneration, but there are so many dead scrapers or dead links, its tough to validate all of the new URLS being correct without opening up and checking everyone.  

The easier solution would be to chop off the domain for every test - but thats not necessarily the correct one either.  

@mlissner 

In theory, though for most of the functioning scrapers, adding `self.html.rewrite_links(fix_links_in_lxml_tree, base_href==[THE CORRECT URL DOMAIN]` in the testing script during the parse does what we want.

**Comment by flooie** [comment]
That being said - I can certainly go thru and fix every test - it just might take the rest of the day.

**Comment by flooie** [comment]
I also think it would mean requiring that self.url be included in every site object.

**Comment by mlissner** [comment]
Hm, sounds like the status quo is probably OK then, or maybe that making everything just a path might be the better way to go?

**Comment by flooie** [comment]
Im somewhat torn both ways.  

The other solution is to prepare the HTML to have full URLs before adding it to the testing environment.

**Comment by flooie** [comment]
There is something nice about being able to click on a URL generated via the test and seeing if the URL is still valid, but that is also ... a pain.

**Comment by mlissner** [comment]
Yeah, OK, let's go with if it ain't broke don't fix it, in that case. Down the road, maybe, let's address this, if it causes further consternation.

**Comment by flooie** [comment]
Great

**Comment by flooie** [comment]
I suppose @mlissner closing this for now.
