### ISSUE TITLE
Georgia Supreme Parsing Errors

### ISSUE THREAD

**Issue by flooie** [freelawproject/juriscraper#453]
I noticed that the Georgia Supreme Court juriscraper tests are running slowly. 

And I noticed that the case parsing is failing for Substitute opinions.  See: tests/examples/opinions/united_states/ga_example_2.compare.json
```
  'case_dates': '2016-07-14',
   'case_name_shorts': 'PATTERSON',
-  'case_names': 'PATTERSON v. THE STATE 7-25-2016 Substitute Opinion Issued.',
+  'case_names': 'PATTERSON v. State',
   'date_filed_is_approximate': False,
```

**Comment by mlissner** [comment]
Thanks Bill. Grecia, if you can take a look at this one too, that'd be great.
