### ISSUE TITLE
Change citations 

### ISSUE THREAD

**Issue by flooie** [freelawproject/juriscraper#464]
We currently have citations `neutral` `west_state` and `west_citations` in juriscraper.

I can only think of one court where we can acquire (with regularity) multiple citations.  I suggest 
we drop the three citation forms above and replace them with 

`citation` and `parallel_citation` - somewhat surprisingly I think this change will only affect 17 courts.  give or take.

**Comment by mlissner** [comment]
Which citation would go in `citation` and which in `parallel_citation`? I think that'd be a bit confusing to keep track of. Was it hard to do a list of citations in a `citations` key?

**Comment by flooie** [comment]
No, I didn't really even approach it yet because this approach made so much more sense to me personally.  I thought, if we are extracting from a PDF and one from the page, someone grouping them together into a list would be nightmarish.  Just as one example.

**Comment by mlissner** [comment]
Hm, are we doing that anywhere?

**Comment by flooie** [comment]
tax I think - previous to their website changing

**Comment by flooie** [comment]
but perhaps that was dockets,

**Comment by mlissner** [comment]
Well, in any case, I see your point. `parallel` it is.
