### ISSUE TITLE
Can you mark "help wanted" on any scraper tickets that might be easy for someone to pick up?

### ISSUE THREAD

**Issue by jackiekazil** [freelawproject/juriscraper#47]
Can you mark "help wanted" on any scraper tickets that might be easy for someone to pick up?
This is for us to provide challenges during PyCon.. https://us.pycon.org/2015/schedule/presentation/318/

**Comment by brianwc** [comment]
Yes, see Issue #48 for a list of currently problematic scrapers in need of repair. Updated 4/5/15.

**Comment by jackiekazil** [comment]
Thank you!
