### ISSUE TITLE
Help wanted checking the following scrapers

### ISSUE THREAD

**Issue by brianwc** [freelawproject/juriscraper#48]
The following courts generated errors on last run and are likely broken:
(Compare the court website's most recent opinion with https://courtlistener.com 's latest opinion from that court.) 
 - [ ] [colo](http://www.cobar.org/opinions/index.cfm?courtid=2) Last opinion in CL is  2/17/15.
 - [x] [nh](http://www.courts.state.nh.us/supreme/opinions/2015/index.htm) Last opinion in CL is 1/22/15. ***FIXED BY PR #51***
 - [ ] [ri](https://www.courts.ri.gov/Courts/SupremeCourt/Opinions/Forms/Standard.aspx) Missing lots of recent opinions.
 - [ ] [ohio](http://www.sconet.state.oh.us/) Last opinion in CL is 2/10/15.
 - [x] [ohioctapp](http://www.sconet.state.oh.us/) Something amiss (all 12 districts) since 2/9/15.
 - [x] ala See Issue #46 It may be that we can stop using alanic.
 - [x] [vt](http://libraries.vermont.gov/law/supreme_court) ***FIXED AS OF 6/4/15***
 - [x] [idahoctapp](http://www.isc.idaho.gov/appeals-court/coa_criminal) Last criminal opinion in CL is  2/26/15. 
 - [x] [sd](http://ujs.sd.gov/Supreme_Court/opinions.aspx) Last opinion in CL is 1/28/15. ***FIXED AS OF 6/4/15***
 - [x] [fladistctapp](https://edca.1dca.org/opinions.aspx) Last opinion in CL is 4/1/15.
 - [ ] [nev](http://nvcourts.gov/) Last opinion in CL is 2/24/15.
 - [x] [mo](https://www.courts.mo.gov/page.jsp?id=12086&dist=Opinions%20Supreme&date=all&year=2015#all) Last opinion in CL is 3/14/15.
 - [x] [moctapp](https://www.courts.mo.gov/page.jsp?id=12086&dist=Opinions%20Eastern&date=all&year=2015#all) Last opinion in CL is 3/13/15. (Link is to Eastern only; check all districts).
 - [x] [connappct](http://www.jud.ct.gov/external/supapp/archiveAROap15.htm) Last opinion in CL is 3/31/15.
 - [x] Idaho Civil
 - [x] Kentucky

**Comment by brianwc** [comment]
ky (Kentucky Supreme Court) should be checked because we've seen some evidence that they have started using a different internal IP address, which sadly must be hard-coded. We've now seen http://162.114.92.72/ whereas the code refers to http://162.114.92.78/. Suggest we create a list of IP addresses we encounter and when one fails we try another. But note, as of May 28, 2015 it at least seems to still be retrieving recent opinions. Whether it is getting ALL of them or whether there might be gaps is what should be checked.

**Comment by mlissner** [comment]
KY is now upgraded according to your suggestion above. It currently has two IP addresses that it tries in succession. Each time an IP fails, it logs an error and tries the next one. If the last IP fails, it raises an error, as you'd expect.

**Comment by mlissner** [comment]
MO was an interesting one. They use an Extended Validation certificate for their HTTPS, which used a certificate authority that our (oldish) version of requests didn't support. In newer versions of requests, they use a separate library called `certifi` that stays up to date with the latest certificates in Mozilla's Cert Store, but in our version, we don't get the most recent certificates.

The change I made makes it so that without updating our version of requests (which would take some work), we now use the `certifi` library in our code.

**Comment by mlissner** [comment]
@m4h7 has completed this. He's a hero.
