### ISSUE TITLE
Juriscraper should use html markup to divide paragraphs of opinion text

### ISSUE THREAD

**Issue by ellliottt** [freelawproject/juriscraper#49]
Parsing the text of the newly scraped opinions is much more difficult than those taken from other sources, since it doesn't include the <p> markup annotating new paragraphs.

**Comment by mlissner** [comment]
CourtListener extracts the opinion text from the PDFs with pdftotext, which does a pretty rotten job of it. We could certainly do better using something like pdfjs, but haven't found resources for it yet.

I'm actually going to close this issue as a dup of that one: freelawproject/courtlistener#248.
