### ISSUE TITLE
Add NDA support to @recap.email

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/juriscraper#533]
After reviewing the error on [#2145](https://github.com/freelawproject/courtlistener/issues/2145) we realized that is due to a parsing error originated because these notifications are NDA (Notice of Docket Activity).

Some changes on `NotificationEmail` are needed in order to parse properly NDA notifications and get their metadata and send docket alerts based on these notifications.

**Comment by albertisfu** [comment]
@mlissner some questions about this:

I saw that NDAs are notifications specifically for appellate courts.

If I'm not wrong. The metadata that we need to fill an appellate case is similar that the retrieved by `AppellateDocketReport`, right?

Comparing some test examples I can see that some data are not available in NDAs and seems mandatory in order to add a new docket for an appellate case, e.g:
`appeal_from, fee_status, originating_court_information, panel`

![Screen Shot 2022-08-10 at 11 40 39](https://user-images.githubusercontent.com/486004/183965908-2cc7b549-d97a-49e7-9683-ad5b2c0ca49c.png)

To retrieve the document for this kind of case seems possible. I saw that since there's no document number the `pacer_doc_id` is used. Also seems that the document link in NDAs is also a free-look download link.

What should we do if we receive an NDA for a case that doesn't exist in CL already?
Should we only add the document as an orphan document?

**Comment by mlissner** [comment]
Seems like the missing piece is:

> Comparing some test examples I can see that some data are not available in NDAs and seems mandatory in order to add a new docket for an appellate case, e.g: appeal_from, fee_status, originating_court_information, panel

Why do you say those are mandatory?

**Comment by albertisfu** [comment]
Sorry I got confused because of this code:
![Screen Shot 2022-08-10 at 13 28 20](https://user-images.githubusercontent.com/486004/183989280-33cd9263-ff55-473d-af22-ceacf921592e.png)
(but this is just for updating metadata)

I've done a test removing these fields that we don't have in an NDA and the docket was added even though some fields are blank.

So yes, seems it's possible to add the docket and documents from NDAs, working on it.
