### ISSUE TITLE
Create scraper for Board of Immigration Appeals (BIA)

### ISSUE THREAD

**Issue by mlissner** [freelawproject/juriscraper#54]
There's a pretty great collection of decisions going all the way back to 1960, many including summaries here:

www.justice.gov/eoir/ag-bia-decisions

A user just suggested that we should add this, and they're absolutely right. It'd be killer to get these included.

**Comment by mlissner** [comment]
Note that we should set blocked to True for these by default.

**Comment by esbranson** [comment]
There are so many more non-judicial judicial bodies that should be included, especially at the state level where their mere existence is a mystery to most lawyers and politicians.

**Comment by brianwc** [comment]
Yes! There's a space on our [juriscraper wiki](https://github.com/freelawproject/juriscraper/wiki/Court-Websites) to list administrative boards that should get covered at some point.

**Comment by mlissner** [comment]
Brian, you should be happy this one is getting merged. Brace for more BIA opinions in a website near you.
