### ISSUE TITLE
Errors in running the commands in the README.md

### ISSUE THREAD

**Issue by Lucioric2000** [freelawproject/juriscraper#550]
The command specified in the README, PYTHONPATH=`pwd` python  juriscraper/sample_caller.py, brings out an error, as does the line PYTHONPATH=`pwd` juriscraper/pacerdocket.py tests/examples/pacer/dockets/district/nysd.html.

**Comment by mlissner** [comment]
What errors and what are you trying to do? The readme probably just needs some tweaks.

**Comment by Lucioric2000** [comment]
for example, PYTHONPATH=`pwd` in the README should be python sample_caller.py, because sample_caller.py is in the git root folder. I am preparing a pull request for this issue, and my CLA.
