### ISSUE TITLE
NEFs docket entry new description markup

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/juriscraper#567]
Monitoring new NDAs support I noticed that we haven't added docket entries from some NEFs.

Reviewing the issue seems this is due to a change in the HTML docket entry description in some courts.

Now we parse the description with these two HTML markups:
```
<p>
<strong>Docket Text:</strong>
<BR>
<FONT  FACE="arial,helvetica" COLOR="#0000cc" SIZE=3><b>
  MOTION to Dismiss for Failure to State 
a Claim <i>the Amended Complaint and Defendant A&M Tobacco, Inc.s Crossclaim</i> 
  by Premiumestore, LLC. (Hanes, Patrick)
</b></Font>
</p>
```

```
<p>
<strong>Docket Text:</strong>
<br>
<b><span>
  MOTION for Partial Summary Judgment 
<i>on Liability</i>  by United States of America, ex rel, filed.  Motion 
Docket Date  8/31/2022.  (Attachments:  # (1) Exhibit 1, # (2) Exhibit 2, 
# (3) Proposed Order Proposed Order)(Redlinger, Julie)
</span></b>
</p>
```

This is the new markup:
```
<p><strong>Docket Text:</strong>
<BR>
Request for courtesy Notice of Electronic Filing (NEF) <i></i>  Filed by Smith, Valerie.   (Smith, Valerie)
</p>
```

Right now if we can't get the description we don't add the docket entry so it's a fundamental field to parse. Should we fail it loud when we can't get the description? instead of returning a None value

**Comment by mlissner** [comment]
Yep. Let's fix this as a priority, and fail loud.

**Comment by mlissner** [comment]
This looks fixed?
