### ISSUE TITLE
Update AttachmentPage report to support a new version of attachment page.

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/juriscraper#579]
There is a new version of AttachmentPage with checkboxes that might be affecting parsing it properly.

![Screen Shot 2022-11-01 at 13 14 43](https://user-images.githubusercontent.com/486004/199318984-20cee666-88e0-4892-bfb6-577e16848628.png)

We need to add support to this new attachment page version.

**Comment by albertisfu** [comment]
I've done some research on this issue.

Seems that there is no problem parsing this attachment page version with Juriscraper, it's properly parsed:

```
{
  "attachments": [
    {
      "attachment_number": 1,
      "description": "Exhibit 1",
      "file_size_str": "337.3 KB",
      "pacer_doc_id": "095011399008",
      "pacer_seq_no": "162",
      "page_count": 9
    },
    {
      "attachment_number": 2,
      "description": "Exhibit 2",
      "file_size_str": "192.2 KB",
      "pacer_doc_id": "095011399009",
      "pacer_seq_no": "162",
      "page_count": 6
    },
    {
      "attachment_number": 3,
      "description": "Exhibit 3",
      "file_size_str": "1.6 MB",
      "pacer_doc_id": "095011399010",
      "pacer_seq_no": "162",
      "page_count": 37
    }
  ],
  "document_number": 63,
  "file_size_str": "195.9 KB",
  "pacer_case_id": "235649",
  "pacer_doc_id": "095011399007",
  "pacer_seq_no": "162",
  "page_count": 17
}
```

I did a test uploading in my local environment first the HTML docket and then the attachment page for this document via recap API.

They were properly added:

![Screen Shot 2022-11-02 at 16 05 45](https://user-images.githubusercontent.com/486004/199616385-b22caf7e-1d3a-4bf6-bc9c-40bb43b50a36.png)


Checking the `ProcessingQueue` objects related to this case in CL there is not a recent attachment page upload that belongs to this document, actually, there is only one attachment page upload for this case (Docket entry number 1).

So here the problem might be that the Attachment page was not uploaded by the Recap extension and only the document was uploaded without uploading a previous attachment report for that docket entry.

Let me know what you think and if we need further research.

**Comment by mlissner** [comment]
Good enough for me! Thank you.
