### ISSUE TITLE
Add scraper for nevada court of appeals

### ISSUE THREAD

**Issue by mlissner** [freelawproject/juriscraper#60]
Looks like an easy subclass of nev_p.py, but it's actually a court that I don't think we have in CourtListener yet. Been a long time since that happened, so:
- Need to decide what to call this jurisdiction. Probably nevctapp? I can't find any references to it in Blue Book v 19.
- Need to find notes on how to add this to CourtListener, and it's possible we'll need to re-jigger the order of the courts in the modal (this, alas, is done manually).

Anyway, worth doing, since it's not every day we have a new jurisdiction.

**Comment by flooie** [comment]
can believe this is still open.
