### ISSUE TITLE
9th Cir scraper down

### ISSUE THREAD

**Issue by brianwc** [freelawproject/juriscraper#623]
It appears juriscraper has not retrieved [anything](https://www.courtlistener.com/?q=&type=o&order_by=dateFiled%20desc&stat_Precedential=on&stat_Non-Precedential=on&court=ca9) from the 9th Circuit since Sep. 2, 2022.

**Comment by mlissner** [comment]
Thanks. @flooie would you be so good as to take this on?

**Comment by flooie** [comment]
But does anything happen in ca9.

**Comment by mlissner** [comment]
No, pretty boring circuit. The good news is we'll start getting more and more CA9 stuff via RECAP, but, alas, we gotta keep this scraper alive, even for boring jurisdictions like this one.

**Comment by flooie** [comment]
Scraper fixed, and back scraped. 

<img width="883" alt="Screenshot 2023-01-13 at 1 58 51 PM" src="https://user-images.githubusercontent.com/6464529/212397887-f9e19854-3531-40f2-917d-ea3e1bbd60d2.png">
