### ISSUE TITLE
Create mailing list for Juriscraper-related discussion and email notifications

### ISSUE THREAD

**Issue by mlissner** [freelawproject/juriscraper#63]
We should have a mailing list called "juriscraper" where we send the Juriscraper notifcations and other related stuff.

So:

 - [x] Set up new list at: http://lists.freelawproject.org/cgi-bin/mailman/create
 - [ ] Re-configure courtlistener to send to that list using a specific subject line, `[juriscraper-notifications]` perhaps?
 - [x] Update the readme to mention this and put it out on the various Twitters.

**Comment by mlissner** [comment]
@brianwc Looks like I don't have permission to do this. Can you set up the mailing list or, even better, give me permission to do so?

**Comment by brianwc** [comment]
@mike and I are already subscribed. Everyone else can subscribe at:

http://lists.freelawproject.org/cgi-bin/mailman/listinfo/juriscraper

**Comment by mlissner** [comment]
Nice work, thanks. I'm reopening until I can get the CourtListener and Readme steps complete, but those should be pretty quick.
