### ISSUE TITLE
SCOTUS Oral Arg broken?

### ISSUE THREAD

**Issue by mlissner** [freelawproject/juriscraper#632]
A reader reports:

>  Not all of the SCOTUS oral argument audio is being captured/fed by CourtLIstener? See, e.g. today January 09 2023.

I haven't dug in, but @audiodude might this be something you could check on to see if something is busted?

**Comment by audiodude** [comment]
What scraper would that correspond to?

**Comment by audiodude** [comment]
I assume `juriscraper/oral_args/united_states/federal_apellate/scotus.py`? I'll take a look

**Comment by audiodude** [comment]
```
$ PYTHONPATH=. python sample_caller.py -c juriscraper.oral_args.united_states.federal_appellate.scotus
Verbosity is set to: 1

Warning: No such file or directory: /var/log/juriscraper/debug.log. Have you created the directory for the log?
Juriscraper will continue to run, and all logs will be sent to stderr.
Starting up the scraper.
Current court: juriscraper.oral_args.united_states.federal_appellate.scotus
Sent GET request to: http://www.supremecourt.gov/oral_arguments/argument_audio.aspx
2023-01-21 13:46:33,842 - INFO: Now downloading case page at: http://www.supremecourt.gov/oral_arguments/argument_audio.aspx
2023-01-21 13:46:34,511 - INFO: juriscraper.oral_args.united_states.federal_appellate.scotus: Successfully found 34 items.

juriscraper.oral_args.united_states.federal_appellate.scotus: Successfully crawled 34 items.
The scraper has stopped.
```

**Comment by mlissner** [comment]
Hm. They all seem to be there. I'll get back to the person who reported this. Weird. Thanks for looking, @audiodude.

**Comment by mlissner** [comment]
Hm, the person that reported this finally followed up to write:

```
Please see
https://www.courtlistener.com/?type=oa&q=&type=oa&order_by=dateArgued%20desc&court=scotus
and compare to
https://www.supremecourt.gov/oral_arguments/argument_audio/2022#list .
First thing to note is SCOTUS has 34 cases, and CL has 23.

Missing in CourtListener include:

21-1454 OH Adjutant Gen.'s Dept. v. FLRA
21-1271 Moore v. Harper
22-58 United States v. Texas
21-806 Health and Hospital Corp. v. Talevski
21-1168 Mallory v. Norfolk Southern Railway Co.
21-86 Axon Enterprise, Inc. v. FTC
20-1199 Students for Fair Admissions v. President and Fellows of Harvard
21-707 Students for Fair Admissions v. University of NC
```

Any chance you have bandwidth to take another look, @audiodude ?

**Comment by audiodude** [comment]
Sorry, when I visit the first courtlistner.com link in your comment, I get 588 results. Then if I limit to 2022 I get 47: https://www.courtlistener.com/?q=&type=oa&order_by=dateArgued%20desc&argued_after=01%2F01%2F2022&argued_before=01%2F01%2F2023&court=scotus

So I'm not entirely sure what we're looking for. Also, the scraper reports 34 items so if they're not making it to the web interface, I assume it's a different problem in the pipeline somewhere?

**Comment by mlissner** [comment]
You're right. This is in the pipeline. These items aren't getting converted properly and so they don't wind up in Solr. This issue has more details that I just dug up: https://github.com/freelawproject/courtlistener/issues/2538

Closing this one again. Thanks in any case.
