### ISSUE TITLE
Handle Confirmation Free Look Use page for free look recap.email documents.

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/juriscraper#663]
A recap.email user reported that some documents filed through recap.email are marked as sealed, even though they are not sealed on PACER.

The issue is related to a feature called "free-look confirmation option" on PACER. When this option is enabled and a magic link is clicked, instead of directly downloading the PDF, a confirmation page is displayed that requires the user to confirm the download.

![Screenshot 2023-03-27 at 12 51 47](https://user-images.githubusercontent.com/486004/228038542-2586cc76-4fad-4a0f-aef4-a5fd35bbf0c1.png)

Since we mark documents as sealed when we are unable to download them, documents are being incorrectly marked as sealed due to this confirmation page.

To fix this issue, we need to be able to detect the confirmation page and confirm the download to get the PDF and prevent documents from being incorrectly marked as sealed.

**Comment by mlissner** [comment]
The main question I have with this is whether we can figure out if the docs are sealed when this setting is enabled. Do you have any ideas? If not, it's probably worth investigating that part now and then we can decide if we want to fix it (if we can), depending on how hard that investigation is.

**Comment by albertisfu** [comment]
I believe it won't be difficult to determine if a document is sealed or not. The confirmation page is shown anonymously, without the need of being logged into PACER. Therefore, we can click on the download link when we detect a free-look confirmation page. If we receive the PDF binary, we can assume that the document is not sealed. However, if we get an HTML page again (likely the login page), it means the document is sealed. The PDF response will be `None`, and we'll mark it as sealed.

This is my theory, but we'll need to receive a notification where the free-look confirmation page is enabled and the document is in fact sealed to confirm it. But I'm pretty sure that it should work as described (unless there is another surprise from PACER.)

**Comment by mlissner** [comment]
Great. Let's see if the person raising the issue can clarify this, but it would make sense for you to be right.
