### ISSUE TITLE
Parse docket report properly when "View multiple documents" option is enabled on PACER 

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/juriscraper#687]
When a docket report is queried in PACER and the "View multiple documents" option is enabled.

The docket entries table got an extra column with a checkbox:

![screenshot_1](https://github.com/freelawproject/juriscraper/assets/486004/4797aa70-6c57-4f6b-a96d-8e02973c99c6)

The current issue is that the document number is not being correctly parsed for minute and sealed entries. As a result, entries are being added without numbers, which leads to duplication.

To resolve this problem, we need to identify and accurately parse this version of the docket report. By doing so, minute and sealed entries get entry numbers.

**Comment by mlissner** [comment]
I'm surprised we don't have some tests/parsers for this already. Probably worth checking the test cases real quick. 

Thanks for jumping on this.

**Comment by ttys0dev** [comment]
See related PR #718 which parses the attachment data from the docket rather than ignoring it.
