### ISSUE TITLE
Non-opinions scraped from Neb. Ct. App. 

### ISSUE THREAD

**Issue by cweider** [freelawproject/juriscraper#701]
In CL’s recent listings, I noticed an entry, [Memo Opinons NOT Selected for Posting (Neb. Ct. App. 2023)](https://www.courtlistener.com/opinion/9409545/memo-opinons-not-selected-for-posting/)[sic], that looked suspiciously not opinion-like. There are many of these, all from Neb. Ct. App., and they can be found from the bogus docket [A-XX-XXXX](https://www.courtlistener.com/?docket_number=A-XX-XXXX).

Two examples:
<img width="25%" src="https://github.com/freelawproject/juriscraper/assets/45040/609480f2-5aac-42a2-808c-66c90f0f49f2"> <img width="25%" src="https://github.com/freelawproject/juriscraper/assets/45040/00e6fa70-c970-492b-9468-e4764924081b">

These arise, because the court posts these notes as items in their [weekly announcements of memorandum opinions](https://supremecourt.nebraska.gov/courts/court-appeals/opinions):

<img width="50%" src="https://github.com/freelawproject/juriscraper/assets/45040/a290ecec-e532-479b-98f8-27534518975c">

A small adjustment to `juriscraper/opinions/united_states/state/neb.py` should be enough to stop ingestion. Perhaps followed by a migration removing `A-XX-XXXX`-related content.

**Comment by mlissner** [comment]
Yeah, we should probably fix this. Seems simple enough.
