### ISSUE TITLE
Oregon Supreme Court opinions have no content

### ISSUE THREAD

**Issue by cweider** [freelawproject/juriscraper#707]
For 2019 onwards, the [Oregon Supreme Court opinions](https://www.courtlistener.com/?q=%22please%20enable%20Javascript%20in%20your%20browser%22&type=o&order_by=dateFiled%20asc&stat_Precedential=on) are only the the warning, “Javascript Required: To experience full interactivity, please enable Javascript in your browser.” It looks like the court switch off of plain old HTML and to a JS Web app; the scraper needs to handle this Javascript, find an alternative source, or just upload `null`.

**Comment by mlissner** [comment]
That's not good at all. We need to get some resources to work on our scrapers. They're a bit of a mess.

**Comment by flooie** [comment]
Thats wild.

**Comment by flooie** [comment]
thanks @cweider for finding this.  I've created a fix for it and will remove the years of bad scrapes on CL.

Ive also added in the court of appeals or Oregon now
