### ISSUE TITLE
CA2 Oral Arg Scraper Stopped

### ISSUE THREAD

**Issue by brianwc** [freelawproject/juriscraper#746]
[Nothing new since June of this year](https://www.courtlistener.com/?type=oa&q=&type=oa&order_by=dateArgued%20desc&court=ca2). That's not right.

**Comment by mlissner** [comment]
Our scrapers need love and maintenance, but I've been focused on getting the old stuff done. We can prioritize this though.

**Comment by flooie** [comment]
Fixed
