### ISSUE TITLE
Overview of Current Scrapers

### ISSUE THREAD

**Issue by flooie** [freelawproject/juriscraper#773]
Looking solely at Sentry errors over the last three days- these are the only courts that have active issues. 

Oklahoma appears to be an issue still.  Something about a captcha protections + HTML is causing weirdness 

- [x] Okla
- [x] OklaCivApp
- [x] OklaCrimApp
- [x] OklaAG

Mississippi still blocks our scrapers but maybe we can resolve this soon.
- [ ] Miss
- [ ] MissAppCt

And another check of these courts is needed.  
- [x] `juriscraper.opinions.united_states.federal_appellate.ca10`
- [ ] `juriscraper.opinions.united_states.administrative_agency.bva`

**Comment by flooie** [comment]
Oklahoma should be resolved.

**Comment by mlissner** [comment]
Whoo boy.

**Comment by flooie** [comment]
Currently we are selenium free 

FYI

**Comment by mlissner** [comment]
Pardon me? Like, we can remove it from our infrastructure?

**Comment by flooie** [comment]
Correct.  we no longer use selenium to scrape any website.  Do we want to keep it just in case we come across something?  idk.

**Comment by mlissner** [comment]
Well...it's pretty easy to scale these down and save some memory, so I'm going to do that. If things go sideways, we'll know pretty quickly, I think.

**Comment by flooie** [comment]
BVA should get its own issue and Mississippi has its own.  So im going to close this for now. 

We are going to start generating new issues when the new person starts going thru the system.
