### ISSUE TITLE
Mississippi Scraper Blocked

### ISSUE THREAD

**Issue by flooie** [freelawproject/juriscraper#784]
An email was sent yesterday to ask them to whitelist our IP address

**Comment by flooie** [comment]
Id very much like your input on this one.

**Comment by flooie** [comment]
Mississippi appears to be unblocked.  

I checked it randomly yesterday and while the current code base doesnt work I have a solution. this is not pretty but its functional.

```

import datetime
from datetime import datetime, timedelta
from juriscraper.OpinionSiteLinear import OpinionSiteLinear

class Site(OpinionSiteLinear):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.domain = "https://courts.ms.gov"
        self.court_id = self.__module__
        self.url = "https://courts.ms.gov/appellatecourts/sc/scdecisions.php"
        self.recent_thursday = self.get_recent_thursday()
    def _process_html(self):
        self.parameters = {
            'court': 'SCT',
            'date': self.recent_thursday,
        }
        self.url = "https://courts.ms.gov/appellatecourts/docket/get_hd_file.php"
        self.method = "POST"
        self.html = self._download()

        if not any(["ZIP" in link for link in self.html.xpath("//a/@href")]):
            return
        for row in self.html.xpath('//body/*', recursive=False):
            if row.tag == "br": continue
            if row.tag == "center": continue
            if "WordPerfect/ZIP" in row.text_content():
                case = {}
                continue

            hrefs = row.xpath(".//a")
            if hrefs:
                a = hrefs[0]
                byte_str_slug = a.get("href").strip(".")
                if "https" not in byte_str_slug:
                    formatted_slug = byte_str_slug.replace('\\', '/').strip("/")
                    case['url'] = f"https://courts.ms.gov/appellatecourts/{formatted_slug}"
                else:
                    case['url'] = byte_str_slug
                case['docket'] = a.text_content()
            if row.tag == "b":
                case['docket'] = row.text_content().strip()
            if row.tag == "ul":
                case['name'] = row.xpath(".//b/text()")[0]
            if row.tag == "hr":
                if case.get("url", None) is not None:
                    case['date'] = "2023-12-30"
                    case['status'] = "Published"
                    self.cases.append(case)
                case = {}

    @staticmethod
    def get_recent_thursday():
        days_to_subtract = (datetime.now().weekday() - 3 + 7) % 7
        recent_thursday = datetime.now() - timedelta(days=days_to_subtract)
        return recent_thursday.strftime('%m/%d/%Y')
```

**Comment by flooie** [comment]
They only release opinions on Thursdays and the appeals court only on Tuesdays ....  Im worried that they might block us again so I wonder about embedding a requirement to only run this on Fridays and Wednesdays for the appellate court.

**Comment by flooie** [comment]
I got excited when I was able to scrape Mississippi while working elsewhere for Christmas.  Unfortunately my code no longer works now that I am back at my home address.  

I've had multiple phone calls with Mississippi but I have been unable to make progress.  I think we need to consider other options.

**Comment by mlissner** [comment]
Bummer. Is this a captcha issue? If so, I'm +1 for defeating them, but let's stop after the research stage of this until we've had a change to chat about it.

(Amusingly, a compliance officer for a potential (big) client asked a few days if we defeat captchas in some automated fashion. I was happy to say no at the time, but I guess in the future, the answer may change.)

**Comment by flooie** [comment]
I think its recaptcha - but we aren't getting to the point were they even display a captcha they just axe us early

**Comment by flooie** [comment]
I can access it with a VPN - I am going to reach out to the court again to see if we can get whitelisted.

**Comment by flooie** [comment]
I've had very little luck with our original contact at the Mississippi Courts.  So I contacted the director of Information Technology this morning and hope that restart conversations there.

**Comment by mlissner** [comment]
That's great. Can you  keep your notes about who you contacted, their contact info, and how they responded over in freelawproject/crm, please?

**Comment by flooie** [comment]
This was given up on - but we have an awesome new volunteer uploading these manually.

**Comment by grossir** [comment]
Latest `miss` opinion is from October 16th, 2025
https://www.courtlistener.com/?q=court_id%3Amiss&type=o&order_by=dateFiled%20desc&stat_Published=on

<img width="1406" height="541" alt="Image" src="https://github.com/user-attachments/assets/013ce9e2-4724-4f92-a7bc-59ada4c7397b" />
