### ISSUE TITLE
Virgin Islands Superior Court 

### ISSUE THREAD

**Issue by flooie** [freelawproject/juriscraper#800]
Add Virgin Islands Superior Court.  US Territory

## Background
Virgin Islands Superior Court is an appellate court I believe of consequence on the Virgin Islands.  
They publish a relatively nice website for published and unpublished opinions.  [VI Super Court Website](https://visuperiorcourt.hosted.civiclive.com/court_opinions) 

[Published Opnions](https://superior.vicourts.org/court_opinions/published_opinions)
[Unpublished Opnions](https://superior.vicourts.org/court_opinions/unpublished_opinions)

## The Problem

We don't collect opinions from the Virgin Islands Superior Court

## The solution

Build a web scraper for the courts published and unpublished opinions, including test cases using the existing framework.

When published and unpublished opinions are on separate webpages, like in this court, we usually divide up our scrapers into two files, with one inheriting from the other.  See Kansas Supreme Court for an example.  

The scraper should utilized OpinionSiteLinear and should collect the required information.

1. Case Caption (case name)
2. Date (date filed)
3. Case Number (Docket Number)
4. Judge	
5. Citation
6. Status (as published or unpublished)
7. URL 

## Bonus Points for using a deferring list to collect  

8. Summaries 

## Side notes 

This court has an ID in [courts-db](https://github.com/freelawproject/courts-db) of VISUPER - which should be the naming convention used for the court in juriscraper.  In this case, the files should be named `visuper_p.py` and `visuper_u.py` (for published and unpublished opinions).

**Comment by agarzaarvizu** [comment]
Hi @flooie, 

I just finished the code, but I'm not allowed to create my branch and push my commit.

**Comment by flooie** [comment]
Hi @agarzaarvizu that's great to hear.  

I think what you want to do is fork the juriscraper repository and then make a PR from your fork. You should find more information about [this process here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).

**Comment by agarzaarvizu** [comment]
Hi @flooie,

Done, I have created the PR linked to this issue, I did everything you asked but the bonus point related to the summary, I didn't understand that point, if you think is a must, I would like to check an example or something that can give me an idea of what you're looking for, but at this moment the scraper is done.

Feel free to do some comments or asked anything else.

Regards

**Comment by agarzaarvizu** [comment]
@flooie Just to let you know, the testing jobs are failing because of this issue in the Virginia scraper:

> FAIL: test_scrape_opinion_state_example_files (test_ScraperExampleTest.ScraperExampleTest.test_scrape_opinion_state_example_files) [Testing example files] (json_path='tests/examples/opinions/united_states/va_example.compare.json', module_string='juriscraper.opinions.united_states.state.va')
Traceback (most recent call last):
  File "/home/runner/work/juriscraper/juriscraper/tests/local/test_ScraperExampleTest.py", line 110, in run_tests_on_module_str
    self.assertEqual(
AssertionError: 4 != 3 : Fixture and scraped data have different lengths: expected 4 and scraped 3 (juriscraper.opinions.united_states.state.va)

**Comment by flooie** [comment]
@agarzaarvizu Thanks - I've fixed the `va` test that was failing.

**Comment by agarzaarvizu** [comment]
@flooie I've rebased my branch and the tests in the PR have passed successfully!
