### ISSUE TITLE
Bankruptcy Appellate Panel 1st Circuit

### ISSUE THREAD

**Issue by flooie** [freelawproject/juriscraper#822]
URL: `https://www.bap1.uscourts.gov/bapopn`

Add Bankruptcy Appellate Panel 1st Circuit

## Background
Bankruptcy Appellate Panel 1st Circuit is an appellate bankruptcy court. I believe of consequence on the Virgin Islands.  
They publish a relatively nice website for published and unpublished opinions.  [BAP1](https://www.bap1.uscourts.gov/bapopn) 

## The Problem

Build a web scraper for bankruptcy Appellate Panel First Circuit including test cases using the existing framework. 

The scraper should utilized OpinionSiteLinear and should collect the required information.

<img width="1198" alt="Screenshot 2023-12-15 at 10 58 29 AM" src="https://github.com/freelawproject/juriscraper/assets/6464529/1bd46f98-3069-4232-968c-4c9ea10c0fa9">

1. Short title (case name)
2. Pub Date (date filed)
3. DocketSheet (Docket Number)
4. Lower Court (District)	
5. Status (as published or unpublished) - Look for the P or U at the end of the docket number in column 1
6. URL 

# The Solution 

Should use `OpinionSiteLinear` and should follow the convention of and use `_process_html`.  

Bap1 displays its data in chronological order.  And one of the things we try to avoid is over using a court website.  So - this scraper should utilize the [date search](https://www.bap1.uscourts.gov/opn) page to fine tune the query.  The time range is usually dependent on how often a court publishes opinions.  Here the frequency is not often, so a query over for the last month may be appropriate.  

# Bonus Points

Back Scraper

For a recent implementation `back scraper` can be found in the CA2 oral arguments scraper.

**Comment by flooie** [comment]
# Postscript 

[this case](https://www.bap1.uscourts.gov/sites/bap1/files/bap.pdf.opinions/96-035P1.pdf) I found in your test file.

You can see that the docket number is actually  `BAP No. RI 96-035` a format that you could identify correctly from the html columns

**Comment by grossir** [comment]
Will work on it, thanks for the extra info

**Comment by flooie** [comment]
@grossir - this is a relatively straightforward a scraper/backscraper but it can still be tricky.  Feel free to ask questions here or via email if you prefer.

**Comment by grossir** [comment]
> # Postscript
> [this case](https://www.bap1.uscourts.gov/sites/bap1/files/bap.pdf.opinions/96-035P1.pdf) I found in your test file.
> 
> You can see that the docket number is actually `BAP No. RI 96-035` a format that you could identify correctly from the html columns
> 
> Both docket number and status are going to need/want separate methods to build those values. Nothing complicated.

I can see when opening the documents that the docket number preprends the lower court abbreviation. 

That data point could be extracted in 2 ways:
- opening the PDF and extracting the full docket number from the first page (may be a little heavier on processing and network)
- using the lower court  / district info to get the abbreviation from there. For example, "Rhode Island" -> "RI". This option seems better

Is there any place where I can get the mapping from full court name to abbreviation? 

All other observations have been updated in the PR, if you want to check them

**Comment by flooie** [comment]
So - if you are paying attention. you have to view a handful - 
massachussets (Boston) goes to >MB
Mass. (Springfield) -> MS
Maine (portland) -> EP
Maine (Bangor) -> EB
All Rhode Island go to RI 
All New Hampshire go to NH

**Comment by grossir** [comment]
> So - if you are paying attention. you have to view a handful - massachussets (Boston) goes to >MB Mass. (Springfield) -> MS Maine (portland) -> EP Maine (Bangor) -> EB All Rhode Island go to RI All New Hampshire go to NH

I ended up extracting the abbrevations from the known cases

```{python}
import re
import pdfplumber
from io import BytesIO
import requests

seen_courts = {}

# all_cases: contains all the cases scraped by the backscraper, may be obtained from a custom caller

for case in all_cases:
    lower_court = case['lower_court']
    
    if lower_court not in seen_courts:
        pdf = pdfplumber.open(BytesIO(requests.get(case['url']).content))
        first_page_text = pdf.pages[0].extract_text()
        docket_number = case['docket']
        try:
            full_docket_number = re.search(rf'\s+.*{docket_number}\s+', first_page_text).group(0)
        except AttributeError:
            print(first_page_text, docket_number, case)
            continue
        seen_courts[lower_court] = full_docket_number.strip().split(' ')[-2]
```

Yields the following mapper which has been included on the bap1 file

```{python}
lower_court_to_abbreviation = {
        "USBC - District of New Hampshire": "NH",
        "USBC - District of Massachusetts (Worcester)": "MW",
        "USBC - District of Puerto Rico": "PR",
        "USBC - District of Massachusetts (Boston)": "MB",
        "USBC - District of Maine (Portland)": "EP",
        "USBC - District of Rhode Island": "RI",
        "Bankrupcty Court of ME - Bangor": "EB",
        "Bankruptcy Court of MA - Boston": "MB",
        "Bankruptcy Court of MA - Springfield": "MS",
        "Bankruptcy Court of ME - Portland": "EP",
        "Bankruptcy Court - Rhode Island": "RI",
        "Bankruptcy Court - San Juan Puerto Rico": "PR",
        "Bankruptcy Court of MA - Worcester": "MW",
        "Bankruptcy Court - Ponce Puerto Rico": "PR",
        "Bankruptcy Court of NH, Concord": "NH",
    }
```


This process also surfaces a dirty case, where the docket number taken from the HTML does not match the one on the PDF
```
In [23]: case
Out[23]: 
{'status': 'Unknown',
 'url': 'https://www.bap1.uscourts.gov/sites/bap1/files/bap.pdf.opinions/96-004O1.pdf',
 'docket': '96-004',
 'date': '2001/09/07',
 'name': 'Perlman v. Tenofsky',
 'lower_court': 'USBC - District of Massachusetts (Boston)'}

In [24]: first_page_text
Out[24]: "UNITED STATES BANKRUPTCY APPELLATE PANEL\nOF THE FIRST CIRCUIT\nIn re: *\n*\nSTEVEN J. TENOFSKY * BAP NO. 96-1104\nDebtor * 96-1105\n* (Consolidated)\n------------------------------------------------------*\n*\nSTEVEN J. TENOFSKY * Case No. 94-17454-CJK\nDefendant * ADV. No. 95-1117\nAppellant * 95-1335\n*\nv. *\n*\nSAMUEL PERLMAN & *\nHERBERT RUBIN, *\nTrustees of H.D.S. Realty Trust *\n*\nand *\n*\nJOSEPH BRAUNSTEIN *\nTrustee of Steven J. Tenofsky *\nPlaintiffs *\nAppellees *\n------------------------------------------------------*\nBefore VOTOLATO, LAMOUTTE and DE JESUS, U.S. Bankruptcy Judges.\nORDER\nThe debtor appeals the bankruptcy court's denial of discharge in his chapter 7 case\npursuant to 11 U.S.C. § 727(a)(3). The appeal came before the panel for oral argument on\nDecember 17, 1996.\nBackground\nDebtor filed his petition for relief under chapter 7 of the Bankruptcy Code on\nNovember 11, 1994 (case no. 94-17454-CJK). This is debtor's third petition. The previous\ncase was filed on August 9, 1988 (case no. 88-11454-CJK)."

```

**Comment by flooie** [comment]
Excellent new scraper.  @grossir - only thing left is to bump juriscraper here - and update the dependencies in Courtlistener
