### ISSUE TITLE
Maine Superior Court 

### ISSUE THREAD

**Issue by flooie** [freelawproject/juriscraper#840]
https://mainelaw.maine.edu/library/collections/superior-court-decisions/

Not sure if this is the right place, but we may want to add the Maine Superior Court sooner rather than later 
considering they just entered into the media frenzy from the primary

https://www.washingtonpost.com/politics/2023/12/28/maine-trump-primary-ballot/

**Comment by mlissner** [comment]
This is the right place to propose new courts, yep.

**Comment by flooie** [comment]
I meant - not sure if this is the right place to scrape from.  But I think it is.
