### ISSUE TITLE
calag: official citation available but not parsed

### ISSUE THREAD

**Issue by grossir** [freelawproject/juriscraper#884]
"Official citation" strings appear for some cases:
![image](https://github.com/freelawproject/juriscraper/assets/14970769/50970d1d-8a29-4ade-849c-3269941ab86a)

We are not picking up the citation's on courtlistener: See [23-602](https://www.courtlistener.com/opinion/9454483/untitled-california-attorney-general-opinion/?q=court_id%3Acalag&type=o&order_by=dateFiled%20desc&stat_Precedential=on)

**Comment by flooie** [comment]
fixed
