### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by mlissner** [freelawproject/juriscraper#93]
In particular, `python-dateutil` is crashing in tests when the latest version is used.

**Comment by arderyp** [comment]
is this still relevant?

**Comment by mlissner** [comment]
Yes. The trick here is that we need to update these lockstep with CourtListener. As I understand it (and perhaps it's worth double checking this), if two libraries call for the same dependency, the newer one will just be chosen. So I *think* if we upgrade things here, that'll upgrade things for CourtListener as well. But I'm not sure how it really works. 

I did just upgrade lxml and selenium though, and I did them lockstep with CL and it wasn't that bad.

**Comment by arderyp** [comment]
do juriscraper and cl share unified processes?  or do they share the same virtualenv?

**Comment by mlissner** [comment]
Same env, yeah.

Le sam. 30 mai 2020 à 09:41, Philip Ardery <notifications@github.com> a
écrit :

**Comment by arderyp** [comment]
why would two separate apps with separate requirements.txt files share the same env?  Regardless, I think its good to strive to keep all packages up to date, as letting things fall behind become an exponential nightmare to cleanup later.

**Comment by mlissner** [comment]
Maybe I misunderstand how virtualenvs work, but if CourtListener requires juriscraper, how can it have a separate env?

Agree about updates. That's kind of where things are at the moment — a nightmare.

**Comment by arderyp** [comment]
oh, juriscraper is only installed as a dependency of CL?  Maybe the problem here is that I don't really understand how CL and juriscraper interact with each other.  However you set it up is probably correct and I'm just misunderstanding the setup.

**Comment by flooie** [comment]
I think we can move on from this issue - seems like we've done quite a lot of updates on dependencies @mlissner - feel free to correct me if im wrong here

**Comment by mlissner** [comment]
Yeah, I'm OK closing this. Libraries should have liberal requirements, locking to the lowest version they support. Websites should have tight requirements, locking to the latest version, period.

So long as Juriscraper isn't holding us (or others) back, I'm cool. A test would be to export requirements.txt from CL. Remove Juriscraper and export again. If any deps are newer, then Juriscraper is an issue. But I'm not too worried about it generally.
