### ISSUE TITLE
Support start and end values to create backscraper iterable

### ISSUE THREAD

**Issue by grossir** [freelawproject/juriscraper#942]
### Current behaviour

All `back_scrape_iterable` are hardcoded. If not strictly in their values, in the start and end values for their creation.
For example:
```
        self.back_scrape_iterable = list(range(2003, date.today().year + 1))
```

### Desired behavior
Pass the start and end of the range as optional keyword arguments, and generate the range from that. Default values could be set as the current harcoded values.
This would allow to backscrape dynamically the date range where we know we have a gap #929 .
We would need to support this on Courtlistener cl_back_scrape_opinions command, too

**Comment by flooie** [comment]
Thanks @grossir  - a nice update.
