### ISSUE TITLE
Normalize docket_number from FreeOpinionReport

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/juriscraper#953]
In [#3541](https://github.com/freelawproject/courtlistener/issues/3541) , we noticed that `FreeOpinionReport` docket number is being parsed differently than from `DocketReport`.

![Screenshot 2024-03-12 at 15 47 57](https://github.com/freelawproject/juriscraper/assets/486004/d0eb8902-ffe2-4bd5-af11-cddcdf0b107a)

For instance in this example the docket number returned by the `FreeOpinionReport` is `2:23-cv-08966-DSF-E`, while the one returned by the DocketReport is `2:23-cv-08966`.

We should normalize the `FreeOpinionReport` to parse the docket_number as `2:23-cv-08966`

**Comment by mlissner** [comment]
Is this one completed via freelawproject/juriscraper#953?

**Comment by albertisfu** [comment]
Correct, this is completed.
